#!/usr/bin/env python3

"""Module handling SmartFuzz."""

# Standard Library
import json
import math
import os

from typing import Dict, List, Optional, Tuple

# Third Party
from solc_json_parser.parser import SolidityAst

# Library
from smartbench import issue, logger
from smartbench.annotation import BugAnnot
from smartbench.docker import DockerContainer
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.printer import debug, error, error_traceback, safe_print, warning
from smartbench.solidity.loc import Location
from smartbench.tools.tool import Tool
from smartbench.solidity import solc


class Smartfuzz(Tool):
    def __init__(
        self,
        id: str,
        root_id: str,
        name: str,
        executable: str,
        default_arguments: str,
        default_timeout: int,
        additional_args: Optional[str] = None,
        random_seed: int = 0,
    ):
        Tool.__init__(
            self,
            id,
            root_id,
            name,
            executable,
            default_arguments,
            default_timeout,
            additional_args,
            random_seed,
        )

    def make_analysis_command(
        self,
        test_file: str,
        contracts: List[str],
        test_output_dir: str,
        container: DockerContainer,
        solc_version: str,
        timeout: Optional[int] = None,
    ) -> str:
        """Function to make analysis command for `Smartfuzz`. This function
        should have the same signature with other tools."""

        # Executable file
        cmd = f"docker exec -it {container.name} /root/{self.executable}"

        # Input file
        cmd += f" -f {test_file}"

        # Specify the input contract name if there is only 1 target contract.
        # Otherwise, let SmartFuzz handle all the contract name automatically
        # if annot_format != "solidifi" and len(contracts) == 1:
        #     cmd += f" --contract-name {contracts[0]}"

        # disable --use-symbolic-execution for now
        # move --use-dependency-graph --use-delta-debugging --enable-abstract-rewriting
        # from run-smartbench.sh to here for reusability of docker image
        cmd += " --use-dependency-graph --use-delta-debugging --enable-abstract-rewriting "
        # Solc version
        if solc_version is not None:
            cmd += f" --solc-version {solc_version}"
        # Output files
        if output_file := self.configure_json_result_file(test_output_dir):
            cmd += f" -r {output_file}"
        if coverage_file := self.configure_json_coverage_file(test_output_dir):
            cmd += f" --coverage {coverage_file}"

        # SmartFuzz allows specifying only 1 input contract. If multiple
        # contracts are supplied, let it run automatically.
        if len(contracts) == 1:
            cmd += f" -c {contracts[0]}"

        # Timeout
        timeout = self.default_timeout if timeout is None else timeout
        cmd += f" -t {str(timeout)}"
        cmd += " --time-distribution default"

        # Finally, pass default and additional arguments
        if self.default_arguments:
            cmd += f" {self.default_arguments}"
        if self.additional_args:
            cmd += f" {self.additional_args}"

        return cmd

    def parse_issue_location(
        self,
        test_file: Optional[str],
        contract_name: str,
        func_name: str,
        lines: List[int],
    ) -> List[Location]:
        """Parse source location in backtrace elements generated by smartfuzz."""
        start_line = end_line = None
        if isinstance(lines, list) and len(lines) == 2:
            start_line = int(lines[0])
            end_line = int(lines[1])
        else:
            start_line = end_line = int(lines[0])

        loc = Location(
            None if test_file is None else os.path.basename(test_file),
            contract_name,
            func_name,
            start_line=start_line,
            end_line=end_line,
        )
        return [loc]

    def parse_rule(self, rule: str) -> Checker:
        """Parser checker of Smartfuzz"""
        return Checker("Smartfuzz", rule)

    def parse_issue_kind(self, description: str) -> IssueKind:
        """Parse issue kind from issue description reported by Smartfuzz"""
        # print ("parse issue kind description: ", description)
        if "IntegerOverflow" in description:
            return IssueKind.INTEGER_OVERFLOW

        if "IntegerSubUnderflow" in description:
            return IssueKind.INTEGER_UNDERFLOW

        if "PossibleIntegerTruncation" in description:
            return IssueKind.INTEGER_TRUNCATION

        if "AddressValidation" in description:
            return IssueKind.LACK_OF_ZERO_ADDRESS_VALIDATION

        if "AssertionFailure" in description:
            return IssueKind.ASSERTION_FAILURE

        if "TimestampDependency" in description:
            return IssueKind.BLOCK_VALUE_DEPENDENCY

        if "BlockNumberDependency" in description:
            return IssueKind.BLOCK_VALUE_DEPENDENCY

        if "BlockValueDependency" in description:
            return IssueKind.BLOCK_VALUE_DEPENDENCY

        if "LockedEthers" in description:
            return IssueKind.LOCKING_ETHER

        if "TxOriginDependency" in description:
            return IssueKind.AUTHORIZATION_THROUGH_TX_ORIGIN

        if "REENTRANCY" in description:
            return IssueKind.REENTRANCY

        if "UnauthorizedSend" in description:
            return IssueKind.UNCHECKED_SEND_ETHER

        if "UNSAFE_SELFDESTRUCT" in description:
            return IssueKind.UNSAFE_SELFDESTRUCT

        if "POSSIBLE_ACCESS_CONTROL" in description:
            return IssueKind.ACCESS_CONTROL

        if "EXCEPTION_DISORDER" in description:
            return IssueKind.UNHANDLED_EXCEPTION

        if "UNSAFE_DELEGATECALL" in description:
            return IssueKind.UNSAFE_DELEGATECALL

        if "OUTOFGAS" in description:
            return IssueKind.DENIAL_OF_SERVICE

        safe_print(f"unknown issue kind:{description}")
        return IssueKind.UNKNOWN

    def construct_ast(self, filename: str):
        # Construct AST of test file to get bug location
        ast = None
        if filename is not None:
            best_solc_versions = solc.detect_best_solc_versions(filename)
            for solc_version in best_solc_versions:
                try:
                    ast = SolidityAst(filename, version=solc_version)
                    if ast is not None:
                        break
                except Exception:
                    continue
        if ast is None:
            warning(f"Failed to get AST of: {filename}")

        return ast

    def parse_analysis_output(
        self,
        test_output_dir: str,
    ) -> Optional[List[Issue]]:
        """Parse output of Smartfuzz. Return a list of detected issues, or
        `None` if the result parsing fails."""
        output = None

        test_file = None
        if (log_file := self.configure_log_file(test_output_dir)) is not None:
            test_file = logger.get_input_test_file(log_file)

        if (
            output_file := self.configure_json_result_file(test_output_dir)
        ) is None:
            error("Failed to configure Smartfuzz output file!")
            return None

        try:
            with open(output_file, "r", encoding="utf-8") as file:
                output = json.load(file)
        except Exception:
            error_traceback(f"Failed to parse Smartfuzz output: {output_file}")
            return None

        all_issues = []
        reported_bugs = list(output.values())
        all_issues: List[Issue] = []
        func_loc_dict: Dict[Tuple[str, str], Tuple[int, int]] = {}
        for bug in reported_bugs:
            checker = self.parse_rule("fuzzing")
            issue_kind = self.parse_issue_kind(bug.get("bug_type"))
            contract = bug.get("contract")
            function = bug.get("function")
            start_l = end_l = None
            if issue_kind == IssueKind.DENIAL_OF_SERVICE:
                if (contract, function) in func_loc_dict:
                    (start_l, end_l) = func_loc_dict[(contract, function)]
                else:
                    ast = self.construct_ast(test_file)
                    if ast is not None:
                        try:
                            function_info = ast.function_by_name(contract, function)
                            (start_l, end_l) = function_info.line_num
                            # Store function location for later use
                            func_loc_dict[(contract, function)] = (
                                start_l,
                                end_l,
                            )
                        except Exception:
                            continue

                # Report the whole function for `DENIAL_OF_SERVICE`
                location = self.parse_issue_location(
                    test_file,
                    contract,
                    function,
                    [start_l, end_l]
                )
            else:
                location = self.parse_issue_location(
                    test_file,
                    contract,
                    function,
                    bug.get("line_number"),
                )
            all_issues = issue.record_new_issue_and_deduplicate(
                all_issues,
                issue_kind,
                "",
                location,
                checker,
            )

        return all_issues

    def match_location_of_issue_to_annotation(
        self, issue: Issue, annot: BugAnnot
    ) -> bool:
        """Function to check whether an reported issue is related to a bug
        annotation."""

        for iloc in issue.locations:
            # Check whether the issue location is covered by the annotation
            # location.
            if iloc.start_line is None or iloc.end_line is None:
                return False

            # Checking for `DENIAL_OF_SERVICE` issue
            if (issue.issue_kind == IssueKind.DENIAL_OF_SERVICE
                and annot.start_line >= iloc.start_line
                and annot.end_line <= iloc.end_line
            ):
                return True

            # Checking whether the annotation location covers the issue
            # location detected by SmartFuzz
            if (
                iloc.start_line >= annot.start_line
                and iloc.end_line <= annot.end_line
            ):
                return True

        return False
