#!/usr/bin/env python3

"""Module handling SmartFuzz."""

# Standard Library
import json
import os
import shlex
import subprocess

from typing import List, Union

# Third Party
import toml

# Library
from smartbench import log
from smartbench.debug import debug, warning
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.location import Location


# Tool name
TOOL_NAME = "smartfuzz"

def install_virtual_env():
    print("install_virtual_env for smartfuzz")
    command = "sh smartbench/tools/smartfuzz/install_smartfuzz.sh"
    # print("command: ", command)
    try: subprocess.run(
            shlex.split(command),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
            )
    except ValueError:
        print("Fail to run command: ", str(command))

def make_smartfuzz_analysis_command(
    executable_file: str,
    arguments: str,
    test_file: str,
    output_file: str,
    solc_path: str,
):
    """
    Function to make analysis command for Smartfuzz.
    This function should have the same signature with other tools.
    """
    command = executable_file

    if arguments:
        command = command + " " + arguments

    command = (
        command
        + " --path "
        + test_file
        + " -r "
        + output_file
        + " --rust-evm"
        + " --trials 40000"
    )

    print(f"command: {command}");
    return command


def parse_confidence(confidence: Union[str, None]) -> Confidence:
    """Parse confidence level of issue detected by Smartfuzz."""
    if confidence is None:
        return Confidence.UNKNOWN

    confidence = confidence.casefold()

    if confidence == "high":
        return Confidence.HIGH

    if confidence == "low":
        return Confidence.LOW

    if confidence == "medium":
        return Confidence.MEDIUM

    return Confidence.UNKNOWN


def parse_severity(severity: Union[str, None]) -> Severity:
    """Parse severity level of issue detected by Smartfuzz."""
    if severity is None:
        return Severity.UNKNOWN

    severity = severity.casefold()

    if severity == "optimization":
        return Severity.CODE_OPTIMIZATION

    if severity == "informational":
        return Severity.INFORMATIONAL

    if severity == "low":
        return Severity.LOW_RISK

    if severity == "medium":
        return Severity.MEDIUM_RISK

    if severity == "high":
        return Severity.HIGH_RISK

    return Severity.UNKNOWN


def parse_source_location(log_file, backtrace_elements) -> Location:
    """Parse source location in backtrace elements generated by Smartfuzz."""
    if len(backtrace_elements) == 0:
        test_file = log.get_input_test_file(log_file)
        return Location(test_file)

    buggy_element = backtrace_elements[0]
    source_mapping = buggy_element.get("source_mapping")
    file_name = source_mapping.get("filename_absolute")
    lines = source_mapping.get("lines")
    start_line = lines[0]
    end_line = lines[len(lines) - 1]
    start_column = source_mapping.get("starting_column")
    end_column = source_mapping.get("ending_column")

    return Location(file_name, start_line, start_column, end_line, end_column)


def parse_rule(rule: str) -> Checker:
    """Parser checker of Smartfuzz"""
    return Checker("Smartfuzz", rule)


def parse_issue_kind(description: str, checker: str) -> IssueKind:
    """Parse issue kind from issue description reported by Smartfuzz"""

    return IssueKind.UNKNOWN


def parse_smartfuzz_json_output(
    output_file: str,
    log_file: str,
) -> List[Issue]:
    """Parse output of Smartfuzz"""
    output = None

    debug("Smartfuzz parse file: ", output_file)
    with open(output_file, "r", encoding="utf-8") as file:
        try:
            output = json.load(file)
        except ValueError:
            warning("Failed to parse Smartfuzz output file:", output_file)
            return []

    if output is None:
        warning("Failed to parse Smartfuzz's output file:", output_file)
        return []

    try:
        success = output.get("success")
        if not success:
            warning("An error happened when running Smartfuzz!")
            warning("See output file for more details: " + output_file)
            return []

        results = output.get("results")
        detectors = results.get("detectors")

        issues = []

        for detector in detectors:
            description = detector.get("description")
            checker = parse_rule(detector.get("check"))
            kind = parse_issue_kind(description, checker.detector)
            location = parse_source_location(log_file, detector.get("elements"))
            severity = parse_severity(detector.get("impact"))
            confidence = parse_confidence(detector.get("confidence"))
            issue = Issue(
                kind,
                description,
                severity,
                confidence,
                location,
                checker,
            )
            issues.append(issue)

        return issues
    except ValueError:
        return []
