#!/usr/bin/env python3

"""Module handling SmartFuzz."""

# Standard Library
import json
import math
import os

from typing import List, Optional, Union

# Library
from smartbench.annotation import BugAnnot
from smartbench.docker import DockerContainer
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.printer import debug, error, error_traceback
from smartbench.solidity.loc import Location
from smartbench.tools.tool import Tool


# Configure some paths
SMARTFUZZ_DIR = os.path.dirname(__file__)


class Smartfuzz(Tool):
    def __init__(
        self,
        id: str,
        name: str,
        executable: str,
        default_arguments: str,
        default_timeout: int,
        additional_args: Optional[str] = None,
        random_seed: int = 0,
    ):
        Tool.__init__(
            self,
            id,
            name,
            executable,
            default_arguments,
            default_timeout,
            additional_args,
            random_seed,
        )

    def make_analysis_command(
        self,
        test_file: str,
        contracts: List[str],
        test_output_dir: str,
        solc_version: Optional[str] = None,
        container: Optional[DockerContainer] = None,
        timeout: Optional[int] = None,
    ) -> str:
        """Function to make analysis command for `Smartfuzz`. This function
        should have the same signature with other tools."""

        # Executable file
        if container is not None:
            cmd = f"docker exec -it {container.name} /root/{self.executable}"
        else:
            cmd = os.path.join(SMARTFUZZ_DIR, self.executable)

        # Input file and contract names
        cmd += " -f " + test_file
        if len(contracts) > 0:
            cmd += " -c " + " ".join(contracts)

        # Solc version
        if solc_version is not None:
            cmd += " --solc-version " + solc_version

        # Output directory and result file file
        cmd = cmd + " -o " + test_output_dir
        if output_file := self.configure_json_output(test_output_dir):
            cmd += " -r " + output_file

        # Calculate timeout for each contract if it is not specified in
        # additional arguments of Confuzzius
        if (
            self.additional_args is None
            or "--time " not in self.additional_args
        ):
            timeout = self.default_timeout if timeout is None else timeout
            contract_timeout = math.ceil(timeout / len(contracts))
            cmd += " -t " + str(contract_timeout)

        # Random seed
        cmd += " --seed " + str(self.random_seed)

        # Finally, pass default and additional arguments
        if self.default_arguments:
            cmd = cmd + " " + self.default_arguments
        if self.additional_args:
            cmd = cmd + " " + self.additional_args

        return cmd

    def parse_source_location(self, line) -> Union[Location, None]:
        """Parse source location in backtrace elements generated by smartfuzz."""
        if isinstance(line, list) and len(line) == 2:
            return Location("", int(line[0]), 0, int(line[1]), 0)
        else:
            return Location("", int(line), 0, (line), 0)

    def parse_rule(self, rule: str) -> Checker:
        """Parser checker of Smartfuzz"""
        return Checker("Smartfuzz", rule)

    def parse_issue_kind(self, description: str) -> IssueKind:
        """Parse issue kind from issue description reported by Smartfuzz"""
        # print ("parse issue kind description: ", description)
        if "IntegerOverflow" in description:
            return IssueKind.INTEGER_BUG

        if "IntegerSubUnderflow" in description:
            return IssueKind.INTEGER_BUG

        if "IntegerSubUnderflow" in description:
            return IssueKind.INTEGER_BUG

        if "AddressValidation" in description:
            return IssueKind.LACK_OF_ZERO_ADDRESS_VALIDATION

        if "AssertionFailure" in description:
            return IssueKind.ASSERTION_FAILURE

        if "TimestampDependency" in description:
            return IssueKind.BLOCK_DEPENDENCY

        if "BlockNumberDependency" in description:
            return IssueKind.BLOCK_DEPENDENCY

        if "TxOriginDependency" in description:
            return IssueKind.TX_ORIGIN_USAGE

        if "REENTRANCY" in description:
            return IssueKind.REENTRANCY

        if "UnauthorizedSend" in description:
            return IssueKind.UNCHECKED_SEND

        if "UNSAFE_SELFDESTRUCT" in description:
            return IssueKind.UNSAFE_SELFDESTRUCT

        if "POSSIBLE_ACCESS_CONTROL" in description:
            return IssueKind.ACCESS_CONTROL

        if "EXCEPTION_DISORDER" in description:
            return IssueKind.UNHANDLED_EXCEPTION

        if "PossibleIntegerTruncation" in description:
            return IssueKind.INTEGER_BUG

        print("unknown issue kind: ", description)
        return IssueKind.UNKNOWN

    def parse_analysis_output(
        self,
        test_output_dir: str,
    ) -> Optional[List[Issue]]:
        """Parse output of Smartfuzz. Return a list of detected issues, or
        `None` if the result parsing fails."""
        output = None

        if (output_file := self.configure_json_output(test_output_dir)) is None:
            error("Failed to configure Smartfuzz output file!")
            return None

        debug("Smartfuzz parse file: ", output_file)

        try:
            with open(output_file, "r", encoding="utf-8") as file:
                output = json.load(file)
        except Exception:
            error_traceback(f"Failed to parse Smartfuzz output: {output_file}")
            return None

        all_issues = []
        reported_bugs = list(output.values())
        for bug in reported_bugs:
            checker = self.parse_rule("fuzzing")
            kind = self.parse_issue_kind(bug.get("bug_type"))
            location = self.parse_source_location(bug.get("line_number"))
            issue = Issue(
                kind,
                "",
                Severity.UNKNOWN,
                Confidence.UNKNOWN,
                location,
                checker,
            )
            all_issues.append(issue)
        return all_issues

    def check_issue_kind(
        self, issue_kind: IssueKind, annotation_kind: IssueKind
    ) -> bool:
        """Function to check whether an reported issue is related to a bug"""
        return issue_kind == annotation_kind

    def match_location_of_issue_to_annotation(
        self, issue: Issue, annot: BugAnnot
    ) -> bool:
        """Function to check whether an reported issue is related to a bug
        annotation."""

        # Check for issue kind
        if not self.check_issue_kind(issue.issue_kind, annot.annot_kind):
            return False
        iloc: Location = issue.location
        debug(
            "match_location_of_issue_to_annotation: ",
            iloc,
            annot.start_line,
            annot.end_line,
        )
        # Check whether the issue location is covered by the annotation location.
        if iloc.start_line is None or iloc.end_line is None:
            return False
        # Pass all criteria to match an issue with a bug annotation
        return (
            iloc.start_line >= annot.start_line
            and iloc.end_line <= annot.end_line
        )
