#!/usr/bin/env python3

"""Module handling sFuzz."""

# Standard Library
import math
import os
import re

from typing import List, Optional, Tuple, Union

# Library
from smartbench import logger, solc
from smartbench.annotation import BugAnnot
from smartbench.docker import DockerContainer
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.loc import Location
from smartbench.printer import debug, warning
from smartbench.tools.tool import Tool

SFUZZ_DIR = os.path.dirname(__file__)


class Sfuzz(Tool):
    def __init__(
        self,
        id: str,
        name: str,
        executable: str,
        default_arguments: str,
        default_timeout: int,
        additional_args: Optional[str] = None,
    ):
        Tool.__init__(
            self,
            id,
            name,
            executable,
            default_arguments,
            default_timeout,
            additional_args,
        )

    def make_analysis_command(
        self,
        test_file: str,
        contracts: List[str],
        test_output_dir: str,
        container=Optional[DockerContainer],
        timeout: Optional[int] = None,
    ) -> str:
        """
        Function to make analysis command for Slither.
        This function should have the same signature with other tools.
        """

        if container is not None:
            cmd = f"docker exec -it {container.name} /root/{self.executable}"
        else:
            cmd = os.path.join(SFUZZ_DIR, self.executable)

        # Input file must be the first argument to be run by docker
        cmd = cmd + " " + test_file

        # Pass contract names to Smartian
        if len(contracts) > 0:
            cmd = cmd + " -c " + " ".join(contracts)


        # Pass arguments
        if self.default_arguments:
            cmd = cmd + " " + self.default_arguments
        if self.additional_args:
            cmd = cmd + " " + self.additional_args

        # Timeout
        timeout = self.default_timeout if timeout is None else timeout
        contract_timeout = math.ceil(timeout / len(contracts))

        cmd = cmd + " -t " + str(contract_timeout)

        return cmd

    def parse_issue_location(self, log_file) -> Union[Location, None]:
        """Parse source location in backtrace elements generated by sFuzz."""
        file_path = logger.get_input_test_file(log_file)
        return Location(file_path, 0, 0, 0, 0)

    def parse_issue_kind(self, description: str) -> IssueKind:
        if "exception disorder : found" in description:
            return IssueKind.UNHANDLED_EXCEPTION

        if "reentrancy : found" in description:
            return IssueKind.REENTRANCY

        if "integer overflow : found" in description:
            return IssueKind.INTEGER_BUG

        if "integer underflow : found" in description:
            return IssueKind.INTEGER_BUG

        if "dangerous delegatecall : found" in description:
            return IssueKind.UNSAFE_DELEGATECALL

        if "freezing ether : found" in description:
            return IssueKind.LOCKING_ETHER

        if "block number dependency : found" in description:
            return IssueKind.BLOCK_DEPENDENCY

        if "timestamp dependency : found" in description:
            return IssueKind.BLOCK_DEPENDENCY

        return IssueKind.UNKNOWN

    def parse_analysis_output(self, test_output_dir: str) -> List[Issue]:
        """Parse output of sFuzz"""
        lines = None
        log_file = os.path.join(test_output_dir, self.log_file)
        debug("sFuzz log_file: ", log_file)
        with open(log_file, "r", encoding="utf-8") as file:
            try:
                lines = [line.rstrip() for line in file]
            except ValueError:
                warning("Failed to parse sFuzz log file:", log_file)
                return []

        if lines is None:
            warning("Failed to parse sFuzz log file:", log_file)
            return []

        kinds = []
        checker = Checker("sFuzz", "fuzzing")

        for line in lines:
            kind = self.parse_issue_kind(line)
            if kind != IssueKind.UNKNOWN:
                if kind not in kinds:
                    kinds.append(kind)

        issues = []
        location = self.parse_issue_location(log_file)
        for kind in kinds:
            issue = Issue(
                kind,
                "",
                Severity.UNKNOWN,
                Confidence.UNKNOWN,
                location,
                checker,
            )
            issues.append(issue)

        return issues

    def match_location_of_issue_to_annotation(
        self, issue: Issue, annot: BugAnnot
    ):
        """Function to check whether an reported issue is related to a bug
        annotation."""
        # Check for issue kind
        return issue.issue_kind == annot.annot_kind

    def parse_instruction_coverage(self, test_output_dir: str):
        """Parse instruction coverage of sFuzz"""
        lines = None
        log_file = os.path.join(test_output_dir, self.log_file)
        with open(log_file, "r", encoding="utf-8") as file:
            try:
                lines = [line.rstrip() for line in file]
            except ValueError:
                warning("Failed to parse sFuzz log file:", log_file)
                return []

        contract_coverage = [(0)]
        contract_coverage_list = []
        for line in lines:
            match_str = re.search(r"coverage : [0-9]+", line)
            fuzz_match = re.search(r">> Fuzz", line)
            if fuzz_match:
                if contract_coverage != [(0)]:
                    contract_coverage_list.append(contract_coverage)
                    contract_coverage = [(0)]

            if match_str:
                coverage = match_str.group()
                coverage = coverage.removeprefix("coverage : ")
                contract_coverage.append(int(coverage))

        # Add the results of the last contract
        if contract_coverage != [(0)]:
            contract_coverage_list.append(contract_coverage)

        return contract_coverage_list

