[info]
id = "toolname"
name = "ToolName"
homepage = "https://github.com/tool/toolname"
category = "Static analysis"

[command]
path = "..."
default_arguments = ""

[output]
result_file = "toolname_result.json"
log_file = "toolname_log.toml"
