[info]
id = "sFuzz"
name = "sFuzz"
homepage = "https://github.com/thanhtoantnt/sFuzz"
category = "Fuzzing tool"

[command]
path = "sh smartbench/tools/sfuzz/sfuzz.sh"
default_arguments = ""
default_timeout = 60
