[info]
id = "sFuzz"
name = "sFuzz"
homepage = "https://github.com/duytai/sFuzz"
category = "Fuzzing tool"

[command]
path = "sh smartbench/tools/sfuzz/sfuzz.sh"
default_arguments = ""

[output]
result_file = "sFuzz_result.json"
log_file = "sFuzz_log.toml"
