#!/usr/bin/env python3

"""Module handling sFuzz."""

import os
import subprocess
import shlex

from typing import List, Union

# Library
from smartbench import log
from smartbench.debug import debug, warning
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.location import Location

# Tool name
TOOL_NAME = "sFuzz"

def make_sfuzz_analysis_command(
    executable_file: str,
    arguments: str,
    test_file: str,
    output_file: str,
    solc_path: str,
):
    """
    Function to make analysis command for Slither.
    This function should have the same signature with other tools.
    """
    command = executable_file

    dir_path = os.path.dirname(os.path.realpath(__file__))
    print(dir_path)

    normal_contract = "NormalAttacker_0_4.sol"
    reentrancy_contract = "ReentrancyAttacker_0_4.sol"

    normal_contract = os.path.join(dir_path, normal_contract)
    reentrancy_contract = os.path.join(dir_path, reentrancy_contract)
    if arguments:
        command = command + " " + arguments

    solc_version = os.path.basename(solc_path)
    solc_version.removeprefix("solc-")
    solc_cmd = "solc-select install " + solc_version + "; solc-select use " + solc_version;
    try:
        subprocess.run(
            shlex.split(solc_cmd),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False
        )
    except ValueError:
        print("Failed to run command: " + str(solc_cmd))

    print(f"path: {solc_path}")

    output = subprocess.run(
        shlex.split("solc --version"),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False
    )

    print("solc version: ", output)

    command = (
        command
        + " "
        + test_file
        # + " "
        # + solc_path
        + " "
        + output_file
    )
    print(f"sfuzz command: {command}")
    return command

# BlockstateDependency

def parse_rule(rule: str) -> Checker:
    """Parser checker of sFuzz"""
    return Checker("sFuzz", rule)

def parse_source_location(log_file) -> Union[Location, None]:
    """Parse source location in backtrace elements generated by sFuzz."""
    file_path = log.get_input_test_file(log_file)
    return Location(file_path, 0, 0, 0, 0)

def parse_issue_kind(description: str) -> IssueKind:
    if "MishandledException" in description:
        return IssueKind.UNHANDLED_EXCEPTION;

    if "Reentrancy" in description:
        return IssueKind.REENTRANCY

    if "Reentrancy" in description:
        return IssueKind.REENTRANCY

    if "BlockstateDependency" in description:
        return IssueKind.BLOCK_DEPENDENCY

    return IssueKind.UNKNOWN


def parse_sfuzz_json_output(output_file: str, log_file: str) -> List[Issue]:
    """Parse output of sFuzz"""
    lines = None
    debug("sFuzz parse file: ", output_file)
    with open(output_file, "r", encoding="utf-8") as file:
        try:
            lines = [line.rstrip() for line in file]
        except ValueError:
            warning("Failed to parse Confuzzius output file:", output_file)
            return []

    if lines is None:
        warning("Failed to parse Confuzzius's output file:", output_file)
        return []

    issues = []
    checker = parse_rule("fuzzing")
    for line in lines:
        print(f"line: {line}")
        kind = parse_issue_kind(line)
        location = parse_source_location(log_file)
        issue = Issue(
            kind,
            "",
            Severity.UNKNOWN,
            Confidence.UNKNOWN,
            location,
            checker,
        )
        issues.append(issue)
    return issues;


