#!/usr/bin/env python3

"""Module handling sFuzz."""

# Standard Library
import json
import math
import os
import re

from typing import List, Optional, Union

# Library
from smartbench import logger
from smartbench.annotation import BugAnnot
from smartbench.docker import DockerContainer
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.printer import debug, error, safe_print
from smartbench.solidity import solc
from smartbench.solidity.loc import Location
from smartbench.tools.tool import Tool


class Sfuzz(Tool):
    def __init__(
        self,
        id: str,
        name: str,
        executable: str,
        default_arguments: str,
        default_timeout: int,
        additional_args: Optional[str] = None,
    ):
        Tool.__init__(
            self,
            id,
            name,
            executable,
            default_arguments,
            default_timeout,
            additional_args,
        )

    def make_analysis_command(
        self,
        test_file: str,
        contracts: List[str],
        test_output_dir: str,
        solc_version: Optional[str] = None,
        container=Optional[DockerContainer],
        timeout: Optional[int] = None,
    ) -> str:
        """
        Function to make analysis command for Slither.
        This function should have the same signature with other tools.
        """

        # Configure command
        cmd = f"docker exec -it {container.name} /root/{self.executable}"

        # Input file and contract names
        cmd = cmd + " -f " + test_file
        if len(contracts) == 1:
            cmd = cmd + " -c " + contracts[0]

        # Solc version
        if solc_version is not None:
            cmd = cmd + " --solc-version " + solc_version

        # Pass contract names to sFuzz
        if len(contracts) > 0:
            cmd = cmd + " -c " + " ".join(contracts)

        # Timeout
        timeout = self.default_timeout if timeout is None else timeout
        contract_timeout = math.ceil(timeout / len(contracts))
        cmd = cmd + " -t " + str(contract_timeout)

        # Pass arguments
        if self.default_arguments:
            cmd = cmd + " " + self.default_arguments
        if self.additional_args:
            cmd = cmd + " " + self.additional_args

        return cmd

    def parse_issue_location(self, log_file) -> Union[Location, None]:
        """Parse source location in backtrace elements generated by sFuzz."""
        file_path = logger.get_input_test_file(log_file)
        return Location(file_path, 0, 0, 0, 0)

    def parse_issue_kind(self, description: str) -> IssueKind:
        if "exception disorder : found" in description:
            return IssueKind.UNHANDLED_EXCEPTION

        if "reentrancy : found" in description:
            return IssueKind.REENTRANCY

        if "integer overflow : found" in description:
            return IssueKind.INTEGER_OVERFLOW

        if "integer underflow : found" in description:
            return IssueKind.INTEGER_UNDERFLOW

        if "dangerous delegatecall : found" in description:
            return IssueKind.UNSAFE_DELEGATECALL

        if "freezing ether : found" in description:
            return IssueKind.LOCKING_ETHER

        if "block number dependency : found" in description:
            return IssueKind.BLOCK_VALUE_DEPENDENCY

        if "timestamp dependency : found" in description:
            return IssueKind.BLOCK_VALUE_DEPENDENCY

        return IssueKind.UNKNOWN

    def parse_analysis_output(
        self, test_output_dir: str
    ) -> Optional[List[Issue]]:
        """Parse output of sFuzz"""
        log_lines = []
        log_file = self.configure_log_file(test_output_dir)

        debug("sFuzz log_file: ", log_file)
        has_fuzzing_result = False
        try:
            with open(log_file, "r", encoding="utf-8") as file:
                while line := file.readline():
                    line = line.rstrip()

                    if not has_fuzzing_result and "coverage :" in line:
                        has_fuzzing_result = True

                    log_lines.extend(line)
        except Exception as err:
            error(f"Failed to parse sFuzz log file: {log_file}\n\n{err}")
            return None

        if not has_fuzzing_result:
            return None

        kinds = []
        checker = Checker("sFuzz", "fuzzing")

        for line in log_lines:
            kind = self.parse_issue_kind(line)
            if kind != IssueKind.UNKNOWN:
                if kind not in kinds:
                    kinds.append(kind)

        issues = []
        location = self.parse_issue_location(log_file)
        for kind in kinds:
            issue = Issue(
                kind,
                "",
                Severity.UNKNOWN,
                Confidence.UNKNOWN,
                location,
                checker,
            )
            issues.append(issue)

        return issues

    def match_location_of_issue_to_annotation(
        self, issue: Issue, annot: BugAnnot
    ):
        """Function to check whether an reported issue is related to a bug
        annotation."""
        # Check for issue kind
        return issue.issue_kind == annot.annot_issue_kind

    def parse_instruction_coverage(self, test_output_dir: str):
        """Parse instruction coverage of sFuzz"""
        lines = None
        log_file = self.configure_log_file(test_output_dir)
        coverage_file = os.path.join(test_output_dir, self.coverage_json_file)
        try:
            with open(log_file, "r", encoding="utf-8") as file:
                lines = [line.rstrip() for line in file]
        except Exception as err:
            error(f"Failed to parse sFuzz log file: {log_file}\n\n{err}")
            return None

        contract_coverage_list = []
        contract_name = ""
        first_coverage = 0
        contract_coverage = [first_coverage]

        for line in lines:
            match_str = re.search(r"coverage : [0-9]+", line)
            fuzz_match = re.search(r">> Fuzz [a-zA-Z0-9$_]+", line)
            if fuzz_match:
                contract = fuzz_match.group()
                contract_name = contract.removeprefix(">> Fuzz ")
                safe_print(f"contract: {contract_name}")
                if len(contract_coverage) != 1:
                    contract_coverage_list.append(
                        (contract_name, contract_coverage)
                    )
                    contract_coverage = [first_coverage]

            if match_str:
                coverage = match_str.group()
                coverage = coverage.removeprefix("coverage : ")
                contract_coverage.append(int(coverage))

        # Add the results of the last contract

        if contract_coverage != [0]:
            contract_coverage_list.append((contract_name, contract_coverage))

        if contract_coverage_list == []:
            return None

        results_json_obj = {
            "coverage-interval": 1,
        }
        for contract_name, contract_coverage in contract_coverage_list:
            results_json_obj[contract_name] = contract_coverage

        results_json_obj_str = json.dumps(results_json_obj, indent=2)
        debug(f"coverage: {results_json_obj_str}")

        with open(coverage_file, "w", encoding="utf-8") as file:
            file.write(results_json_obj_str)
            file.close()

        return coverage_file
