[info]
id = "slither"
name = "Slither"
homepage = "https://github.com/crytic/slither"
category = "Static analysis"

[command]
local_executable = "run-slither-local.sh"
docker_executable = "..."
default_arguments = ""
default_timeout = 60
