#!/usr/bin/env python3

"""Module handling Slither."""

# Standard Library
import json
import os

from typing import List, Optional

# Library
from smartbench import issue, logger
from smartbench.annotation import AnnotFormat, BugAnnot
from smartbench.docker import DockerContainer
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.printer import debug, error, error_traceback, warning
from smartbench.solidity.loc import Localizer, Location
from smartbench.tools.tool import Tool


class Slither(Tool):
    def __init__(
        self,
        id: str,
        root_id: str,
        name: str,
        executable: str,
        default_arguments: str,
        default_timeout: int,
        additional_args: Optional[str] = None,
    ):
        Tool.__init__(
            self,
            id,
            root_id,
            name,
            executable,
            default_arguments,
            default_timeout,
            additional_args,
        )

    def make_analysis_command(
        self,
        test_file: str,
        contracts: List[str],
        test_output_dir: str,
        container: DockerContainer,
        solc_version: Optional[str],
        timeout: Optional[int] = None,
    ) -> str:
        """Function to make an analysis command for Slither."""

        # Configure command
        cmd = f"docker exec -it {container.name} /root/{self.executable}"

        # Input file
        cmd += f" -f {test_file}"

        # Solc version
        if solc_version is not None:
            cmd += f" --solc-version {solc_version}"

        # Output file
        if output_file := self.configure_json_result_file(test_output_dir):
            cmd += f" -o {output_file}"

        # Finally, pass default and additional arguments
        if self.default_arguments:
            cmd += f" {self.default_arguments}"
        if self.additional_args:
            cmd += f" {self.additional_args}"

        # NOTE: temporarily hardcoded to audit hardhat-based project
        cmd += " --solc-remaps @=benchmarks/audit-dboe-smart-contract/node_modules/@"
        return cmd

    def parse_result_confidence(
        self, confidence: Optional[str]
    ) -> Optional[Confidence]:
        """Parse confidence level of issue detected by Slither."""

        if confidence is None:
            return None

        confidence = confidence.casefold()

        if confidence == "high":
            return Confidence.HIGH_CONFIDENCE

        if confidence == "low":
            return Confidence.LOW_CONFIDENCE

        if confidence == "medium":
            return Confidence.MEDIUM_CONFIDENCE

        warning(f"Unknown confidence: {confidence}")
        return None

    def parse_issue_severity(
        self, severity: Optional[str]
    ) -> Optional[Severity]:
        """Parse severity level of issue detected by Slither."""

        if severity is None:
            return None

        severity = severity.casefold()

        if severity == "optimization":
            return Severity.CODE_OPTIMIZATION

        if severity == "informational":
            return Severity.INFORMATIONAL

        if severity == "low":
            return Severity.LOW_RISK

        if severity == "medium":
            return Severity.MEDIUM_RISK

        if severity == "high":
            return Severity.HIGH_RISK

        warning(f"Unknown severity: {severity}")
        return None

    def parse_issue_location(
        self, log_file: str, backtrace_elements
    ) -> List[Location]:
        """Parse source location in backtrace elements generated by Slither."""
        test_file = logger.get_input_test_file(log_file)
        if test_file is None:
            return []

        if len(backtrace_elements) == 0:
            return [Location(test_file)]

        # Get bug location from the last element in backtrace
        buggy_element = backtrace_elements[0]
        source_mapping = buggy_element.get("source_mapping")

        # Parse file name
        file_name = source_mapping.get("filename_absolute")
        if file_name is None or file_name == "":
            file_name = test_file

        # Parse line and column numbers
        start_line = end_line = start_col = end_col = None
        lines = source_mapping.get("lines")
        if lines:
            start_line = lines[0]
            end_line = lines[len(lines) - 1]
            start_col = source_mapping.get("starting_column")
            end_col = source_mapping.get("ending_column")
        else:
            # Read location from `start` and `end` properties in JSON format
            start = source_mapping.get("start")
            length = source_mapping.get("length")
            localizer = Localizer(file_name)
            if start_loc := localizer.get_line_column_number(start):
                (start_line, start_col) = start_loc
            if end_loc := localizer.get_line_column_number(start + length):
                (end_line, end_col) = end_loc

        loc = Location(
            file_path=file_name,
            start_line=start_line,
            start_column=start_col,
            end_line=end_line,
            end_column=end_col,
        )

        return [loc]

    def parse_issue_kind(self, description: str, checker: str) -> IssueKind:
        """Parse issue kind from issue description reported by Slither"""
        if "Reentrancy in" in description and "reentrancy" in checker:
            return IssueKind.REENTRANCY

        if "ignores return value by" in description:
            if "send" in description:
                return IssueKind.UNCHECKED_SEND_ETHER
            if "transfer" in description:
                return IssueKind.UNCHECKED_TRANSFER_ETHER
            if checker == "unused-return":
                return IssueKind.UNCHECKED_TRANSFER_ETHER
            if checker == "unchecked-lowlevel":
                return IssueKind.UNCHECKED_LOW_LEVEL_CODE

        if "allows anyone to destruct the contract" in description:
            return IssueKind.UNSAFE_SELFDESTRUCT

        if "Low level call" in description:
            return IssueKind.LOW_LEVEL_CALL

        if "incorrect ERC20 function interface" in description:
            return IssueKind.INCORRECT_ERC20_FUNCTION_INTERFACE

        if "lacks a zero-check on" in description:
            return IssueKind.LACK_OF_ZERO_ADDRESS_VALIDATION

        if "sends eth to arbitrary user" in description:
            return IssueKind.UNCHECKED_SEND_ETHER

        if "uses tx.origin for authorization" in description:
            return IssueKind.AUTHORIZATION_THROUGH_TX_ORIGIN

        if "uses assembly" in description:
            return IssueKind.USE_ASSEMBLY

        if "uses delegatecall to a input-controlled function" in description:
            return IssueKind.UNSAFE_DELEGATECALL

        if "uses a weak PRNG" in description:
            return IssueKind.WEAK_PSEUDO_RANDOM_NUMBER_GENERATOR

        if "uses a dangerous strict equality" in description:
            return IssueKind.DANGEROUS_STRICT_EQUALITY

        if "uses timestamp for comparisons" in description:
            return IssueKind.BLOCK_VALUE_DEPENDENCY

        if "should emit an event" in description:
            return IssueKind.SHOULD_EMIT_EVENT

        if "sets array length with a user-controlled value" in description:
            return IssueKind.USER_CAN_MANIPULATE_ARRAY_LENGTH

        if "multiplication on the result of a division" in description:
            return IssueKind.MULTIPLICATION_AFTER_DIVISION

        if "Pragma version" in description:
            if "allows old version" in description:
                return IssueKind.OUTDATED_COMPILER_VERSION
            if "is known to contain severe issues" in description:
                return IssueKind.VULNERABLE_COMPILER_VERSION

        if "is not recommended for deployment" in description:
            return IssueKind.COMPILER_NOT_RECOMMENDED_FOR_DEPLOYMENT

        if "is never initialized. It is used in" in description:
            return IssueKind.UNINITIALIZED_STATE_VARIABLE

        if "is a storage variable never initialized" in description:
            return IssueKind.UNINITIALIZED_STORAGE_VARIABLE

        if "is a local variable never initialized" in description:
            return IssueKind.UNINITIALIZED_STATE_VARIABLE

        if "is set pre-construction with a non-constant" in description:
            if checker == "function-init-state":
                return IssueKind.FUNCTION_INIT_NON_CONSTANT_STATE

        if "should inherit from" in description:
            return IssueKind.MISSING_INHERITANCE

        if "has external calls inside a loop" in description:
            return IssueKind.EXTERNAL_CALLS_INSIDE_LOOP

        if (
            "has payable functions" in description
            and "But does not have a function to withdraw" in description
        ):
            return IssueKind.LOCKING_ETHER

        if "Backdoor function found in" in description:
            return IssueKind.BACKDOOR_FUNCTION

        if "Deprecated" in description:
            if "THROW" in description:
                return IssueKind.DEPRECATED_THROW
            if 'Usage of "suicide()" should be replaced with' in description:
                return IssueKind.DEPRECATED_SUICIDE
            if 'Usage of "msg.gas" should be replaced with' in description:
                return IssueKind.DEPRECATED_MSG_GAS
            if 'Usage of "sha3()" should be replaced' in description:
                return IssueKind.DEPRECATED_SHA3
            if 'Usage of "block.blockhash()" should be replaced' in description:
                return IssueKind.DEPRECATED_BLOCK_DOT_BLOCKHASH

        if "is declared view but contains assembly code" in description:
            return IssueKind.VIEW_FUNCTION_CONTAIN_ASM

        ####################################
        # Coding style

        if "not in mixedCase" in description:
            if "Parameter" in description:
                return IssueKind.PARAMETER_NAME_NOT_IN_MIXED_CASE
            if "Variable" in description:
                return IssueKind.VARIABLE_NAME_NOT_IN_MIXED_CASE
            if "Modifier" in description:
                return IssueKind.MODIFIER_NAME_NOT_IN_MIXED_CASE
            if "Function" in description:
                return IssueKind.FUNCTION_NAME_NOT_IN_MIXED_CASE

        if "not in UPPER_CASE_WITH_UNDERSCORES" in description:
            if "Constant" in description:
                return IssueKind.CONSTANT_NAME_NOT_IN_UPPER_CASE

        if "not in CapWords" in description:
            if "Contract" in description:
                return IssueKind.CONTRACT_NAME_NOT_IN_CAP_WORDS
            if "Struct" in description:
                return IssueKind.STRUCT_NAME_NOT_IN_CAP_WORDS
            if "Event" in description:
                return IssueKind.STRUCT_NAME_NOT_IN_CAP_WORDS

        if "shadows" in description:
            if checker == "shadowing-local":
                return IssueKind.SHADOWING_LOCAL_VARIABLE
            if checker == "shadowing-state":
                return IssueKind.SHADOWING_STATE_VARIABLE
            if checker == "shadowing-abstract":
                return IssueKind.SHADOWING_ABSTRACT_FUNCTION
            if checker == "shadowing-builtin":
                return IssueKind.SHADOWING_BUILTIN_SYMBOL

        if "is too similar to" in description:
            if "Variable" in description:
                return IssueKind.SIMILAR_VARIABLE_NAME

        ####################################
        # Code optimization

        if "compares to a boolean constant" in description:
            return IssueKind.COMPARE_TO_BOOLEAN_CONSTANT

        if "does not always execute" in description:
            return IssueKind.POSIBLE_UNREACHABLE_CODE

        if (
            "is never used and should be removed" in description
            and checker == "dead-code"
        ):
            return IssueKind.UNUSED_FUNCTION

        if "is never used in" in description and checker == "unused-state":
            return IssueKind.UNUSED_VARIABLE

        if "uses literals with too many digits" in description:
            return IssueKind.USE_LITERALS_WITH_TOO_MANY_DIGITS

        if "should be constant" in description:
            return IssueKind.USE_CONSTANT_INSTEAD_OF_VARIABLE

        if "should be declared external" in description:
            return IssueKind.FUNCTION_SHOULD_BE_DECLARED_EXTERNAL

        if "has costly operations inside a loop" in description:
            return IssueKind.COSTLY_LOOP

        if "contains a tautology or contradiction" in description:
            return IssueKind.TAUTOLOGY_OR_CONTRADICTION

        if "Redundant expression" in description:
            return IssueKind.REDUNDANT_EXPRESSION

        return IssueKind.UNKNOWN

    def parse_analysis_output(
        self,
        test_output_dir: str,
    ) -> Optional[List[Issue]]:
        """Parse output of Slither. Return `None` if result parsing is not
        successful."""

        if self.json_result_file is None:
            error_traceback("JSON output file is not found!")
            return None

        output_file = os.path.join(test_output_dir, self.json_result_file)
        log_file = self.configure_log_file(test_output_dir)

        output = None

        debug("Slither parse file: ", output_file)
        try:
            with open(output_file, "r", encoding="utf-8") as file:
                output = json.load(file)
        except Exception as err:
            error(f"Failed to parse Slither output: {output_file}\n\n{err}")
            return None

        success = output.get("success")
        if not success:
            error(f"An error happened when running Slither: {output_file}")
            return None

        try:
            results = output.get("results")
            detectors = results.get("detectors")
        except ValueError:
            return None

        all_issues: List[Issue] = []
        for detector in detectors:
            description = detector.get("description")
            checker = Checker("Slither", detector.get("check"))
            kind = self.parse_issue_kind(description, checker.detector)
            location = self.parse_issue_location(
                log_file, detector.get("elements")
            )
            severity = self.parse_issue_severity(detector.get("impact"))
            confidence = self.parse_result_confidence(
                detector.get("confidence")
            )

            all_issues = issue.record_new_issue_and_deduplicate(
                all_issues,
                kind,
                description,
                location,
                checker,
                severity,
                confidence
            )

        return all_issues

    def match_location_of_issue_to_annotation(
        self, issue: Issue, annot: BugAnnot
    ) -> bool:
        """Matching bug locations of an issue reported by Slither with the
        location of the bug annotation."""

        # Find if a bug location matches with the annotation location.
        for iloc in issue.locations:
            # The bug line number must be reported explicitly by Silther
            if iloc.start_line is None or iloc.end_line is None:
                return False

            if (
                annot.annot_format == AnnotFormat.SMARTBUGS
                or annot.annot_format == AnnotFormat.SMARTBENCH
                or annot.annot_format == AnnotFormat.VERISMART
            ):
                # Slither reports issue location as a range with begin and end
                # line/colum. If an issue and a bug annotation are relevant,
                # then the issue's location should cover the bug annotation's
                # location.
                if (
                    iloc.start_line <= annot.start_line
                    and iloc.end_line >= annot.end_line
                ):
                    return True

            elif annot.annot_format == AnnotFormat.SOLIDIFI:
                #  When the annotation is in SolidiFI format, we need to check
                #  whether the annotation location covers the bug location
                if (
                    iloc.start_line >= annot.start_line
                    and iloc.end_line <= annot.end_line
                ):
                    return True

        return False
