#!/usr/bin/env python3

"""Module handling Slither."""

# Standard Library
import json
import os

from typing import List, Optional, Tuple

# Library
from smartbench import logger, solc
from smartbench.docker import DockerContainer, AnalysisJob
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.loc import Localizer, Location
from smartbench.printer import debug, warning
from smartbench.tools.tool import Tool


SLITHER_DIR = os.path.dirname(__file__)


class Slither(Tool):
    def __init__(
        self,
        id: str,
        name: str,
        executable: str,
        default_arguments: str,
        default_timeout: int,
        additional_args: Optional[str] = None,
    ):
        Tool.__init__(
            self,
            id,
            name,
            executable,
            default_arguments,
            default_timeout,
            additional_args,
        )

    def make_analysis_command(
        self,
        test_file: str,
        contracts: List[str],
        test_output_dir: str,
        container=Optional[DockerContainer],
        timeout: Optional[int] = None,
    ) -> str:
        """
        Function to make an analysis command for Slither.
        """
        if container is not None:
            cmd = f"docker exec -it {container.name} /root/{self.executable}"
        else:
            cmd = os.path.join(SLITHER_DIR, self.executable)

        if self.default_arguments:
            cmd = cmd + " " + self.default_arguments
        if self.additional_args:
            cmd = cmd + " " + self.additional_args

        output_file = self.configure_output_file(test_output_dir)

        return f"{cmd} {test_file} --json {output_file}"

    def parse_result_confidence(self, confidence: Optional[str]) -> Confidence:
        """Parse confidence level of issue detected by Slither."""
        if confidence is None:
            return Confidence.UNKNOWN

        confidence = confidence.casefold()

        if confidence == "high":
            return Confidence.HIGH_CONFIDENCE

        if confidence == "low":
            return Confidence.LOW_CONFIDENCE

        if confidence == "medium":
            return Confidence.MEDIUM_CONFIDENCE

        return Confidence.UNKNOWN

    def parse_issue_severity(self, severity: Optional[str]) -> Severity:
        """Parse severity level of issue detected by Slither."""
        if severity is None:
            return Severity.UNKNOWN

        severity = severity.casefold()

        if severity == "optimization":
            return Severity.CODE_OPTIMIZATION

        if severity == "informational":
            return Severity.INFORMATIONAL

        if severity == "low":
            return Severity.LOW_RISK

        if severity == "medium":
            return Severity.MEDIUM_RISK

        if severity == "high":
            return Severity.HIGH_RISK

        return Severity.UNKNOWN

    def parse_issue_location(self, log_file, backtrace_elements) -> Location:
        """Parse source location in backtrace elements generated by Slither."""
        test_file = logger.get_input_test_file(log_file)
        if len(backtrace_elements) == 0:
            return Location(test_file)

        # Get bug location from the last element in backtrace
        buggy_element = backtrace_elements[0]
        source_mapping = buggy_element.get("source_mapping")

        # Parse file name
        file_name = source_mapping.get("filename_absolute")
        if file_name is None or file_name == "":
            file_name = test_file

        # Parse line and column numbers
        start_line = end_line = start_col = end_col = None
        lines = source_mapping.get("lines")
        if lines:
            start_line = lines[0]
            end_line = lines[len(lines) - 1]
            start_col = source_mapping.get("starting_column")
            end_col = source_mapping.get("ending_column")
        else:
            # Read location from `start` and `end` properties in JSON format
            start = source_mapping.get("start")
            length = source_mapping.get("length")
            localizer = Localizer(file_name)
            if start_loc := localizer.get_line_column_number(start):
                (start_line, start_col) = start_loc
            if end_loc := localizer.get_line_column_number(start + length):
                (end_line, end_col) = end_loc

        return Location(file_name, start_line, start_col, end_line, end_col)

    def parse_issue_kind(self, description: str, checker: str) -> IssueKind:
        """Parse issue kind from issue description reported by Slither"""
        if "Reentrancy" in description:
            return IssueKind.REENTRANCY

        if "ignores return value by" in description:
            if "send" in description:
                return IssueKind.UNCHECKED_SEND
            if checker == "unchecked-lowlevel":
                return IssueKind.UNCHECKED_LOWLEVEL_CODE

        if "Low level call" in description:
            return IssueKind.LOW_LEVEL_CALL

        if "incorrect ERC20 function interface" in description:
            return IssueKind.INCORRECT_ERC20_FUNCTION_INTERFACE

        if "lacks a zero-check on" in description:
            return IssueKind.LACK_OF_ZERO_ADDRESS_VALIDATION

        if "sends eth to arbitrary user" in description:
            return IssueKind.SEND_ETH_TO_ARBITRARY_USER

        if "uses a weak PRNG" in description:
            return IssueKind.WEAK_PSEUDO_RANDOM_NUMBER_GENERATOR

        if "uses a dangerous strict equality" in description:
            return IssueKind.DANGEROUS_STRICT_EQUALITY

        if "uses timestamp for comparisons" in description:
            return IssueKind.USE_BLOCK_TIMESTAMP

        if "should emit an event" in description:
            return IssueKind.SHOULD_EMIT_EVENT

        if "sets array length with a user-controlled value" in description:
            return IssueKind.USER_CAN_MANIPULATE_ARRAY_LENGTH

        if "multiplication on the result of a division" in description:
            return IssueKind.MULTIPLICATION_AFTER_DIVISION

        if "Pragma version" in description:
            if "allows old version" in description:
                return IssueKind.OUTDATED_COMPILER_VERSION

        if "is not recommended for deployment" in description:
            return IssueKind.COMPILER_NOT_RECOMMENDED_FOR_DEPLOYMENT

        if "is a storage variable never initialized" in description:
            return IssueKind.UNINITIALIZED_STORAGE

        if "Deprecated" in description:
            if "THROW" in description:
                return IssueKind.DEPRECATED_THROW
            if 'Usage of "sha3()" should be replaced' in description:
                return IssueKind.DEPRECATED_SHA3
            if 'Usage of "block.blockhash()" should be replaced' in description:
                return IssueKind.DEPRECATED_BLOCK_DOT_BLOCKHASH

        if "compares to a boolean constant" in description:
            return IssueKind.COMPARE_TO_BOOLEAN_CONSTANT

        # Coding style

        if "not in mixedCase" in description:
            if "Parameter" in description:
                return IssueKind.PARAMETER_NAME_NOT_IN_MIXED_CASE
            if "Variable" in description:
                return IssueKind.VARIABLE_NAME_NOT_IN_MIXED_CASE
            if "Modifier" in description:
                return IssueKind.MODIFIER_NAME_NOT_IN_MIXED_CASE
            if "Function" in description:
                return IssueKind.FUNCTION_NAME_NOT_IN_MIXED_CASE

        if "not in UPPER_CASE_WITH_UNDERSCORES" in description:
            if "Constant" in description:
                return IssueKind.CONSTANT_NAME_NOT_IN_UPPER_CASE

        if "shadows:" in description and checker == "shadowing-local":
            return IssueKind.SHADOWING_LOCAL_VARIABLE

        # Code optimization

        if "does not always execute" in description:
            return IssueKind.POSIBLE_UNREACHABLE_CODE

        if (
            "is never used and should be removed" in description
            and checker == "dead-code"
        ):
            return IssueKind.UNUSED_FUNCTION

        if "is never used in" in description and checker == "unused-state":
            return IssueKind.UNUSED_VARIABLE

        if "uses literals with too many digits" in description:
            return IssueKind.USE_LITERALS_WITH_TOO_MANY_DIGITS

        if "should be constant" in description:
            return IssueKind.USE_CONSTANT_INSTEAD_OF_VARIABLE

        if "should be declared external" in description:
            return IssueKind.FUNCTION_SHOULD_BE_DECLARED_EXTERNAL

        if "has costly operations inside a loop" in description:
            return IssueKind.COSTLY_LOOP

        return IssueKind.UNKNOWN

    def parse_analysis_output(
        self,
        test_output_dir: str,
    ) -> List[Issue]:
        """Parse output of Slither"""

        output_file = os.path.join(test_output_dir, self.json_output_file)
        log_file = os.path.join(test_output_dir, self.log_file)

        output = None

        debug("Slither parse file: ", output_file)
        with open(output_file, "r", encoding="utf-8") as file:
            try:
                output = json.load(file)
            except ValueError:
                warning("Failed to parse Slither output file:", output_file)
                return []

        if output is None:
            warning("Failed to parse Slither's output file:", output_file)
            return []

        try:
            success = output.get("success")
            if not success:
                warning("An error happened when running Slither!")
                warning("See output file for more details: " + output_file)
                return []

            results = output.get("results")
            detectors = results.get("detectors")

            issues = []

            for detector in detectors:
                description = detector.get("description")
                checker = Checker("Slither", detector.get("check"))
                kind = self.parse_issue_kind(description, checker.detector)
                location = self.parse_issue_location(
                    log_file, detector.get("elements")
                )
                severity = self.parse_issue_severity(detector.get("impact"))
                confidence = self.parse_result_confidence(
                    detector.get("confidence")
                )
                issue = Issue(
                    kind,
                    description,
                    severity,
                    confidence,
                    location,
                    checker,
                )
                issues.append(issue)

            return issues
        except ValueError:
            return []
