[info]
id = "slither"
name = "Slither"
homepage = "https://github.com/crytic/slither"
category = "Static analysis"

[command]
executable = "run-slither.sh"
default_arguments = ""
default_timeout = 60
