#!/usr/bin/env python3

"""Module handling Mythril."""

# Standard Library
import json
import os

from subprocess import CompletedProcess
from typing import List, Optional

# Third Party
import toml

# Library
from smartbench import bug_annot, log
from smartbench.bug_annot import AnnotFormat, BugAnnot
from smartbench.debug import debug, warning
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.location import Location


# Tool name
TOOL_NAME = "mythril"


def make_analysis_command(
    executable_file: str,
    arguments: str,
    test_file: str,
    output_file: str,
    solc_path: str,
    timeout=60,
):
    """Function to make analysis command for `Mythril`. This function should
    have the same signature with other tools.

    """

    command = executable_file

    solc_version = os.path.basename(solc_path)
    solc_version = solc_version.removeprefix("solc-")

    if arguments:
        command = command + " " + arguments

    command = (
        command
        + " analyze "
        + test_file
        + " --execution-timeout "
        + str(timeout)
        + " --solv "
        + solc_version
        + " -o json  "
        # + output_file
    )

    debug(f"mythril command: {command}")
    return command


def parse_severity(severity: Optional[str]) -> Severity:
    """Parse severity level of issue detected by Mythril."""
    if severity is None:
        return Severity.UNKNOWN

    severity = severity.casefold()

    if severity == "low":
        return Severity.LOW_RISK

    if severity == "medium":
        return Severity.MEDIUM_RISK

    if severity == "high":
        return Severity.HIGH_RISK

    return Severity.UNKNOWN


def parse_source_location(log_file, start_line, end_line) -> Optional[Location]:
    """Parse source location in backtrace elements generated by Mythril."""
    file_path = log.get_input_test_file(log_file)
    return Location(file_path, start_line, 0, end_line, 0)


def parse_rule(rule: str) -> Checker:
    """Parser checker of Mythril"""
    return Checker("mythril", rule)


def parse_issue_kind(description: str) -> IssueKind:
    """Parse issue kind from issue description reported by Mythril"""
    # SWC 127
    # if "Jump to an arbitrary instruction" in description:
    #     return IssueKind.ABITRARY_JUMP

    # SWC 124
    if "Write to an arbitrary storage location" in description:
        return IssueKind.ARBITRARY_WRITE

    # SWC 112
    if "Delegatecall to user-supplied address" in description:
        return IssueKind.UNSAFE_DELEGATECALL

    # SWC 115
    if "Dependence on tx.origin" in description:
        return IssueKind.TX_ORIGIN_USAGE

    # SWC 116 + 120
    if "Dependence on predictable environment variable" in description:
        return IssueKind.BLOCK_DEPENDENCY

    # SWC 105
    if "Unprotected Ether Withdrawal" in description:
        return IssueKind.LEAKING_ETHER

    # SWC 110
    if "Exception State" in description:
        return IssueKind.ASSERTION_FAILURE

    # SWC 107
    if "External Call To User-Supplied Address" in description:
        return IssueKind.REENTRANCY

    # SWC 101
    if "Integer Arithmetic Bugs" in description:
        return IssueKind.INTEGER_BUG

    # # SWC 113
    # if "Multiple Calls in a Single Transaction" in description:
    #     return IssueKind.MULTIPLE_CALLS

    # SWC 107
    if "State access after external call" in description:
        return IssueKind.REENTRANCY

    # SWC 106
    if "Unprotected Selfdestruct" in description:
        return IssueKind.UNSAFE_SELFDESTRUCT

    # SWC 104
    if "Unchecked return value from external call" in description:
        return IssueKind.UNHANDLED_EXCEPTION

    return IssueKind.UNKNOWN


def parse_mythril_json_output(
    output_file: str,
    log_file: str,
) -> List[Issue]:
    """Parse output of Mythril"""
    output = None
    debug("Mythril parse file: ", output_file)
    with open(output_file, "r", encoding="utf-8") as file:
        try:
            output = json.load(file)
        except ValueError:
            warning("Failed to parse Mythril output file:", output_file)
            return []

    try:
        issues = output.get("issues")

        bugs = []

        for issue in issues:
            checker = parse_rule("symbolic execution")
            kind = parse_issue_kind(issue.get("title"))
            start_line = issue.get("lineno")
            code = issue.get("code")
            if code is None:
                end_line = start_line
            else:
                end_line = start_line + code.count("\n")

            location = parse_source_location(log_file, start_line, end_line)
            severity = parse_severity(issue.get("severity"))
            bug = Issue(
                kind,
                "",
                severity,
                Confidence.UNKNOWN,
                location,
                checker,
            )
            bugs.append(bug)

        return bugs
    except ValueError:
        return []


def check_issue_kind(kind: IssueKind, bug_name: str):
    if kind == IssueKind.BLOCK_DEPENDENCY:
        return bug_name == "TIME_MANIPULATION" or bug_name == "BAD_RANDOMNESS"

    if kind == IssueKind.INTEGER_BUG:
        return bug_name == "ARITHMETIC"

    if kind == IssueKind.UNHANDLED_EXCEPTION:
        return bug_name == "UNCHECKED_LL_CALLS"

    if str(kind).casefold() != bug_name.casefold():
        return False
    return True


def match_location_of_issue_to_annotation(issue: Issue, annot: BugAnnot):
    """Function to check whether an reported issue is related to a bug
    annotation."""

    # Check for issue kind
    if not check_issue_kind(issue.issue_kind, annot.bug_name):
        return False

    iloc: Location = issue.location
    # Check whether the issue location is covered by the annotation location.
    if iloc.start_line is None or iloc.end_line is None:
        return False
    if iloc.start_line > annot.start_line + 1:
        return False
    if iloc.end_line < annot.end_line + 1:
        return False

    # Pass all criteria to match an issue with a bug annotation
    return True


def configure_output_file(output_file, result_dir: str) -> str:
    """
    Configure the output file.
    """

    # Prepare output directory
    if not os.path.exists(result_dir):
        os.makedirs(result_dir)

    # Configure output file
    output_file = os.path.join(result_dir, output_file)

    return output_file


def write_to_output_file(
    output: CompletedProcess, file_name: str, benchmark_output_dir: str
):
    output_file = configure_output_file(file_name, benchmark_output_dir)
    f = open(output_file, "w")
    stdout = output.stdout.decode("utf-8")
    json_data = json.loads(stdout)
    json_formatted_str = json.dumps(json_data, indent=2)
    f.write(f"{json_formatted_str}")
    f.close()
