#!/usr/bin/env python3

"""Module handling Mythril."""

# Standard Library
import json
import os

from subprocess import CompletedProcess
from typing import List, Optional, Tuple

# Library
from smartbench import bug_annot, log, solc
from smartbench.bug_annot import BugAnnot
from smartbench.debugger import debug, warning
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.loc import Location
from smartbench.tools.tool import Tool


class Mythril(Tool):
    def __init__(
        self,
        id: str,
        name: str,
        homepage: str,
        category: str,
        path: str,
        default_arguments: str,
        default_timeout: int,
        additional_arguments: Optional[str] = None,
        random_seed: int = 0,
    ):
        Tool.__init__(
            self,
            id,
            name,
            homepage,
            category,
            path,
            default_arguments,
            default_timeout,
            additional_arguments,
            random_seed,
        )

    def make_analysis_command(
        self,
        test_file: str,
        test_output_dir: str,
        timeout=int,
        use_docker=False,
    ) -> Tuple[str, Optional[dict]]:
        """Function to make analysis command for `Mythril`. This function should
        have the same signature with other tools.

        """

        cmd = self.path
        solc_version = solc.detect_required_solc_version(test_file)

        if self.default_arguments:
            cmd = cmd + " " + self.default_arguments
        if self.additional_arguments:
            cmd = cmd + " " + self.additional_arguments

        cmd = (
            cmd
            + " analyze "
            + test_file
            + " --execution-timeout "
            + str(timeout)
            + " --solv "
            + solc_version
            + " -o json  "
        )

        return (cmd, None)

    def parse_severity(self, severity: Optional[str]) -> Severity:
        """Parse severity level of issue detected by Mythril."""
        if severity is None:
            return Severity.UNKNOWN

        severity = severity.casefold()

        if severity == "low":
            return Severity.LOW_RISK

        if severity == "medium":
            return Severity.MEDIUM_RISK

        if severity == "high":
            return Severity.HIGH_RISK

        return Severity.UNKNOWN

    def parse_issue_location(
        self, log_file, start_line, end_line
    ) -> Optional[Location]:
        """Parse source location in backtrace elements generated by Mythril."""
        file_path = log.get_input_test_file(log_file)
        return Location(file_path, start_line, 0, end_line, 0)

    def parse_issue_kind(self, description: str) -> IssueKind:
        """Parse issue kind from issue description reported by Mythril"""
        # SWC 127
        # if "Jump to an arbitrary instruction" in description:
        #     return IssueKind.ABITRARY_JUMP

        # SWC 124
        if "Write to an arbitrary storage location" in description:
            return IssueKind.ARBITRARY_WRITE

        # SWC 112
        if "Delegatecall to user-supplied address" in description:
            return IssueKind.UNSAFE_DELEGATECALL

        # SWC 115
        if "Dependence on tx.origin" in description:
            return IssueKind.TX_ORIGIN_USAGE

        # SWC 116 + 120
        if "Dependence on predictable environment variable" in description:
            return IssueKind.BLOCK_DEPENDENCY

        # SWC 105
        if "Unprotected Ether Withdrawal" in description:
            return IssueKind.LEAKING_ETHER

        # SWC 110
        if "Exception State" in description:
            return IssueKind.ASSERTION_FAILURE

        # SWC 107
        if "External Call To User-Supplied Address" in description:
            return IssueKind.REENTRANCY

        # SWC 101
        if "Integer Arithmetic Bugs" in description:
            return IssueKind.INTEGER_BUG

        # # SWC 113
        # if "Multiple Calls in a Single Transaction" in description:
        #     return IssueKind.MULTIPLE_CALLS

        # SWC 107
        if "State access after external call" in description:
            return IssueKind.REENTRANCY

        # SWC 106
        if "Unprotected Selfdestruct" in description:
            return IssueKind.UNSAFE_SELFDESTRUCT

        # SWC 104
        if "Unchecked return value from external call" in description:
            return IssueKind.UNHANDLED_EXCEPTION

        return IssueKind.UNKNOWN

    def process_analysis_result(self, test_output_dir: str) -> List[Issue]:
        """Parse output of Mythril"""
        output = None
        output_file = os.path.join(test_output_dir, self.output_file)
        log_file = os.path.join(test_output_dir, self.log_file)
        debug("Mythril parse file: ", output_file)
        with open(output_file, "r", encoding="utf-8") as file:
            try:
                output = json.load(file)
            except ValueError:
                warning("Failed to parse Mythril output file:", output_file)
                return []

        try:
            issues = output.get("issues")

            bugs = []

            for issue in issues:
                checker = Checker("mythril", "symbolic execution")
                kind = self.parse_issue_kind(issue.get("title"))
                start_line = issue.get("lineno")
                code = issue.get("code")
                if code is None:
                    end_line = start_line
                else:
                    end_line = start_line + code.count("\n")

                location = self.parse_issue_location(
                    log_file, start_line, end_line
                )
                severity = self.parse_severity(issue.get("severity"))
                bug = Issue(
                    kind,
                    "",
                    severity,
                    Confidence.UNKNOWN,
                    location,
                    checker,
                )
                bugs.append(bug)

            return bugs
        except ValueError:
            return []

    def write_to_output_file(
        self, output: CompletedProcess, benchmark_output_dir: str
    ):
        output_file = self.configure_output_file(benchmark_output_dir)
        f = open(output_file, "w")
        stdout = output.stdout.decode("utf-8")
        json_data = json.loads(stdout)
        json_formatted_str = json.dumps(json_data, indent=2)
        f.write(f"{json_formatted_str}")
        f.close()
