#!/usr/bin/env python3

"""Module handling Mythril."""

# Standard Library
import json
import os

from typing import List, Optional

# Library
from smartbench import logger
from smartbench.docker import DockerContainer
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.printer import debug, error, warning
from smartbench.solidity.loc import Location
from smartbench.tools.tool import Tool


class Mythril(Tool):
    def __init__(
        self,
        id: str,
        name: str,
        executable: str,
        default_args: str,
        default_timeout: int,
        additional_args: Optional[str] = None,
        random_seed: int = 0,
    ):
        Tool.__init__(
            self,
            id,
            name,
            executable,
            default_args,
            default_timeout,
            additional_args,
            random_seed,
        )

    def make_analysis_command(
        self,
        test_file: str,
        contracts: List[str],
        test_output_dir: str,
        solc_version: Optional[str] = None,
        container=Optional[DockerContainer],
        timeout: Optional[int] = None,
    ) -> str:
        """Function to make analysis command for `Mythril`. This function should
        have the same signature with other tools."""

        # Configure command
        cmd = f"docker exec -it {container.name} /root/{self.executable}"

        # Input file and contract names
        cmd = cmd + " -f " + test_file

        # Solc version
        if solc_version is not None:
            cmd = cmd + " --solc-version " + solc_version

        # Output file
        if output_file := self.configure_json_output(test_output_dir):
            cmd = cmd + " -o " + output_file

        # Timeout
        timeout = self.default_timeout if timeout is None else timeout
        cmd = cmd + " -t " + str(timeout)

        # Finally, pass default and additional arguments
        if self.default_arguments:
            cmd = cmd + " " + self.default_arguments
        if self.additional_args:
            cmd = cmd + " " + self.additional_args

        return cmd

    def parse_severity(self, severity: Optional[str]) -> Severity:
        """Parse severity level of issue detected by Mythril."""
        if severity is None:
            return Severity.UNKNOWN

        severity = severity.casefold()

        if severity == "low":
            return Severity.LOW_RISK

        if severity == "medium":
            return Severity.MEDIUM_RISK

        if severity == "high":
            return Severity.HIGH_RISK

        return Severity.UNKNOWN

    def parse_issue_location(
        self, log_file, start_line, end_line
    ) -> Optional[Location]:
        """Parse source location in backtrace elements generated by Mythril."""
        file_path = logger.get_input_test_file(log_file)
        return Location(file_path, start_line, 0, end_line, 0)

    def parse_issue_kind(self, description: str) -> IssueKind:
        """Parse issue kind from issue description reported by Mythril"""
        # SWC 127
        # if "Jump to an arbitrary instruction" in description:
        #     return IssueKind.ABITRARY_JUMP

        # SWC 124
        if "Write to an arbitrary storage location" in description:
            return IssueKind.ARBITRARY_WRITE

        # SWC 112
        if "Delegatecall to user-supplied address" in description:
            return IssueKind.UNSAFE_DELEGATECALL

        # SWC 115
        if "Dependence on tx.origin" in description:
            return IssueKind.TX_ORIGIN_USAGE

        # SWC 116 + 120
        if "Dependence on predictable environment variable" in description:
            return IssueKind.BLOCK_DEPENDENCY

        # SWC 105
        if "Unprotected Ether Withdrawal" in description:
            return IssueKind.LEAKING_ETHER

        # SWC 110
        if "Exception State" in description:
            return IssueKind.ASSERTION_FAILURE

        # SWC 107
        if "External Call To User-Supplied Address" in description:
            return IssueKind.REENTRANCY

        # SWC 101
        if "Integer Arithmetic Bugs" in description:
            return IssueKind.INTEGER_BUG

        # # SWC 113
        # if "Multiple Calls in a Single Transaction" in description:
        #     return IssueKind.MULTIPLE_CALLS

        # SWC 107
        if "State access after external call" in description:
            return IssueKind.REENTRANCY

        # SWC 106
        if "Unprotected Selfdestruct" in description:
            return IssueKind.UNSAFE_SELFDESTRUCT

        # SWC 104
        if "Unchecked return value from external call" in description:
            return IssueKind.UNHANDLED_EXCEPTION

        return IssueKind.UNKNOWN

    def parse_analysis_output(
        self, test_output_dir: str
    ) -> Optional[List[Issue]]:
        """Parse output of Mythril"""
        output = None
        output_file = os.path.join(test_output_dir, self.json_output_file)
        log_file = self.configure_log_file(test_output_dir)
        debug("Mythril parse file: ", output_file)
        try:
            with open(output_file, "r", encoding="utf-8") as file:
                output = json.load(file)
        except Exception as err:
            error(f"Failed to parse Mythril output: {output_file}\n\n{err}")
            return []

        try:
            issues = output.get("issues")

            bugs = []

            for issue in issues:
                checker = Checker("mythril", "symbolic execution")
                kind = self.parse_issue_kind(issue.get("title"))
                start_line = issue.get("lineno")
                code = issue.get("code")
                if code is None:
                    end_line = start_line
                else:
                    end_line = start_line + code.count("\n")

                location = self.parse_issue_location(
                    log_file, start_line, end_line
                )
                severity = self.parse_severity(issue.get("severity"))
                bug = Issue(
                    kind,
                    "",
                    severity,
                    Confidence.UNKNOWN,
                    location,
                    checker,
                )
                bugs.append(bug)

            return bugs
        except ValueError:
            return []
