[info]
id = "mythril"
name = "mythril"
homepage = "https://github.com/ConsenSys/mythril"
category = "Symbolic Execution"

[command]
local_executable = "myth"
docker_executable = "..."
default_arguments = ""
default_timeout = 60
