#!/usr/bin/env python3

"""Module handling ILF."""

# Standard Library
import json
import os

from typing import List, Optional

# Library
from smartbench import logger
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.loc import Location
from smartbench.printer import debug, warning


# Tool name
TOOL_NAME = "ilf"

# def prepare_testing_contract(test_file: str)


def make_analysis_command(
    local_executable_file: str,
    arguments: str,
    test_file: str,
    output_file: str,
    timeout=int,
):
    """Function to make analysis command for `ILF`. This function should
    have the same signature with other tools.

    """
    # TODO
    print("MAKE ILF COMMAND!")
    pass


def parse_confidence(confidence: Optional[str]) -> Confidence:
    """Parse confidence level of issue detected by ILF."""
    # TODO
    pass


def parse_severity(severity: Optional[str]) -> Severity:
    """Parse severity level of issue detected by ILF."""
    # TODO
    pass


def parse_source_location(log_file, backtrace_elements) -> Location:
    """Parse source location in backtrace elements generated by ILF."""
    # TODO
    pass


def parse_rule(rule: str) -> Checker:
    """Parser checker of ILF"""
    # TODO
    pass


def parse_issue_kind(description: str, checker: str) -> IssueKind:
    """Parse issue kind from issue description reported by ILF"""
    # TODO
    pass


def parse_analysis_output(
    output_file: str,
    log_file: str,
) -> List[Issue]:
    """Parse output of ILF"""
    # TODO
    pass
