[info]
id = "ilf"
name = "ILF"
homepage = "https://github.com/eth-sri/ilf"
category = "Fuzzing"

[command]
local_executable = "..."
docker_executable = "..."
default_arguments = ""
default_timeout = 60
