#!/usr/bin/env python3

"""Module handling SMARTIAN."""

# Standard Library
import json
import os

from typing import List, Optional

# Library
from smartbench import log
from smartbench.debug import debug, warning
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.location import Location


# Tool name
TOOL_NAME = "Smartian"


def make_analysis_command(
    executable_file: str,
    arguments: str,
    test_file: str,
    output_file: str,
    solc_path: str,
):
    """Function to make analysis command for `Smartian`. This function should
    have the same signature with other tools.

    """

    command = executable_file

    if arguments:
        command = command + " " + arguments

    solc_version = os.path.basename(solc_path)
    solc_version = solc_version.removeprefix("solc-")
    # TODO: To merge with the timeout from the `tool.py`
    timeout = 30

    command = (
        command
        + " "
        + test_file
        + " "
        + str(timeout)
        + " "
        + solc_version
    )
    print(f"smartian command: {command}")
    return command

def parse_confidence(confidence: Optional[str]) -> Confidence:
    """Parse confidence level of issue detected by SMARTIAN."""
    # TODO
    pass


def parse_severity(severity: Optional[str]) -> Severity:
    """Parse severity level of issue detected by SMARTIAN."""
    # TODO
    pass


def parse_source_location(log_file, backtrace_elements) -> Location:
    """Parse source location in backtrace elements generated by SMARTIAN."""
    # TODO
    pass


def parse_rule(rule: str) -> Checker:
    """Parser checker of SMARTIAN"""
    # TODO
    pass


def parse_issue_kind(description: str, checker: str) -> IssueKind:
    """Parse issue kind from issue description reported by SMARTIAN"""
    # TODO
    pass


def parse_analysis_output(
    output_file: str,
    log_file: str,
) -> List[Issue]:
    """Parse output of SMARTIAN"""
    # TODO
    pass
