#!/usr/bin/env python3

"""Module handling SMARTIAN."""

# Standard Library
import re
import os

from typing import List, Union

# Library
from smartbench import log
from smartbench.debug import debug, warning
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.location import Location


# Tool name
TOOL_NAME = "Smartian"


def make_analysis_command(
    executable_file: str,
    arguments: str,
    test_file: str,
    output_file: str,
    solc_path: str,
):
    """Function to make analysis command for `Smartian`. This function should
    have the same signature with other tools.

    """

    command = executable_file

    if arguments:
        command = command + " " + arguments

    solc_version = os.path.basename(solc_path)
    solc_version = solc_version.removeprefix("solc-")
    # TODO: To merge with the timeout from the `tool.py`
    timeout = 30

    command = (
        command
        + " "
        + test_file
        + " "
        + str(timeout)
        + " "
        + solc_version
        + " "
        + output_file
    )
    print(f"smartian command: {command}")
    return command

def parse_source_location(log_file) -> Union[Location, None]:
    """Parse source location in backtrace elements generated by Smartian."""
    file_path = log.get_input_test_file(log_file)
    return Location(file_path, 0, 0, 0, 0)

def parse_rule(rule: str) -> Checker:
    """Parser checker of Smartian"""
    return Checker("Smartian", rule)

def parse_analysis_output(
    output_file: str,
    log_file: str,
) -> List[Issue]:
    """Parse output of SMARTIAN"""
    debug("sFuzz output_file: ", output_file)
    output_file_data = open(output_file, "r", encoding="utf-8");
    data = output_file_data.read()
    kinds = []

    assert_failure_match = re.search(r"Assertion Failure: [0-9]+", data)
    if assert_failure_match:
        assert_failure = assert_failure_match.group()
        assert_failure_num = assert_failure.removeprefix("Assertion Failure: ")
        if int(assert_failure_num) > 0:
            kinds.append(IssueKind.ASSERTION_FAILURE)

    blk_dep_match = re.search(r"Block state Dependency: [0-9]+", data)
    if blk_dep_match:
        blk_dep = blk_dep_match.group()
        blk_dep_num = blk_dep.removeprefix("Block state Dependency: ")
        if int(blk_dep_num) > 0:
            kinds.append(IssueKind.BLOCK_DEPENDENCY)

    reentrancy_match = re.search(r"Reentrancy: [0-9]+", data)
    if reentrancy_match:
        reentrancy_dep = reentrancy_match.group()
        reentrancy_num = reentrancy_dep.removeprefix("Reentrancy: ")
        if int(reentrancy_num) > 0:
            kinds.append(IssueKind.REENTRANCY)

    checker = parse_rule("fuzzing")
    issues = []
    location = parse_source_location(log_file)
    for kind in kinds:
        issue = Issue(
            kind,
            "",
            Severity.UNKNOWN,
            Confidence.UNKNOWN,
            location,
            checker,
        )
        issues.append(issue)

    return issues;
