#!/usr/bin/env python3

"""Module handling Smartian analyzer."""

# Standard Library
import math
import os
import re

from typing import List, Optional, Tuple, Union

# Library
from smartbench import logger, solc
from smartbench.annotation import BugAnnot
from smartbench.docker import DockerContainer
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.loc import Location
from smartbench.printer import debug, warning, error
from smartbench.tools.tool import Tool


SMARTIAN_DIR = os.path.dirname(__file__)


class Smartian(Tool):
    def __init__(
        self,
        id: str,
        name: str,
        executable: str,
        default_arguments: str,
        default_timeout: int,
        additional_args: Optional[str] = None,
        random_seed: int = 0,
    ):
        Tool.__init__(
            self,
            id,
            name,
            executable,
            default_arguments,
            default_timeout,
            additional_args,
            random_seed,
        )

    def make_analysis_command(
        self,
        test_file: str,
        contracts: List[str],
        test_output_dir: str,
        container=Optional[DockerContainer],
        timeout: Optional[int] = None,
    ) -> str:
        """Function to make analysis command for `Smartian`. This function should
        have the same signature with other tools.

        """

        if container is not None:
            cmd = f"docker exec -it {container.name} /root/{self.executable}"
        else:
            cmd = os.path.join(SMARTIAN_DIR, self.executable)

        # Input file must be the first argument to be run by docker
        cmd = cmd + " -f " + test_file

        # Pass contract names to Smartian
        if len(contracts) > 0:
            cmd = cmd + " -c " + " ".join(contracts)

        # Pass arguments
        if self.default_arguments:
            cmd = cmd + " " + self.default_arguments
        if self.additional_args:
            cmd = cmd + " " + self.additional_args

        # Calculate timeout for each contract if it is not specified in
        # additional arguments of Confuzzius
        if self.additional_args is None or (
            "-t " not in self.additional_args
            and "--timelimit " not in self.additional_args
        ):
            timeout = self.default_timeout if timeout is None else timeout
            contract_timeout = math.ceil(timeout / len(contracts))
            cmd = cmd + " -t " + str(contract_timeout)

        cmd = cmd + " -o " + test_output_dir

        return cmd

    def parse_issue_location(self, log_file) -> Union[Location, None]:
        """Parse source location in backtrace elements generated by Smartian."""
        file_path = logger.get_input_test_file(log_file)
        return Location(file_path, 0, 0, 0, 0)

    def parse_analysis_output(self, test_output_dir: str) -> List[Issue]:
        """Parse analysis result of Smartian."""
        # Smartian does not write output to any JSON file, so we parse its
        # result from the log file.
        log_file = os.path.join(test_output_dir, self.log_file)
        debug("Smartian log file: ", log_file)

        log_file_data = open(log_file, "r", encoding="utf-8")
        data = log_file_data.read()
        kinds = []

        assert_failure_matches = re.findall(r"Assertion Failure: [0-9]+", data)
        for assert_failure_match in assert_failure_matches:
            if IssueKind.ASSERTION_FAILURE not in kinds:
                assert_failure_num = assert_failure_match.removeprefix(
                    "Assertion Failure: "
                )
                if int(assert_failure_num) > 0:
                    kinds.append(IssueKind.ASSERTION_FAILURE)

        arbitrary_write_matches = re.findall(r"Suicidal Contract: [0-9]+", data)
        for arbitrary_write_match in arbitrary_write_matches:
            if IssueKind.ARBITRARY_WRITE not in kinds:
                arbitrary_write_num = arbitrary_write_match.removeprefix(
                    "Suicidal Contract: "
                )
                if int(arbitrary_write_num) > 0:
                    kinds.append(IssueKind.ARBITRARY_WRITE)

        blk_dep_matches = re.findall(r"Block state Dependency: [0-9]+", data)
        for blk_dep_match in blk_dep_matches:
            if IssueKind.BLOCK_DEPENDENCY not in kinds:
                blk_dep_num = blk_dep_match.removeprefix("Block state Dependency: ")
                if int(blk_dep_num) > 0:
                    kinds.append(IssueKind.BLOCK_DEPENDENCY)

        delegatecall_matches = re.findall(r"Control Hijack: [0-9]+", data)
        for delegatecall_match in delegatecall_matches:
            if IssueKind.UNSAFE_DELEGATECALL not in kinds:
                delegatecall_num = delegatecall_match.removeprefix("Control Hijack: ")
                if int(delegatecall_num) > 0:
                    kinds.append(IssueKind.UNSAFE_DELEGATECALL)

        leaking_ether_matches = re.findall(r"Ether Leak: [0-9]+", data)
        for leaking_ether_match in leaking_ether_matches:
            if IssueKind.LEAKING_ETHER not in kinds:
                leaking_ether_num = leaking_ether_match.removeprefix("Ether Leak: ")
                if int(leaking_ether_num) > 0:
                    kinds.append(IssueKind.LEAKING_ETHER)

        integer_matches = re.findall(r"Integer Bug: [0-9]+", data)
        for integer_match in integer_matches:
            if IssueKind.INTEGER_BUG not in kinds:
                integer_num = integer_match.removeprefix("Integer Bug: ")
                if int(integer_num) > 0:
                    kinds.append(IssueKind.INTEGER_BUG)

        exception_matches = re.findall(r"Mishandled Exception: [0-9]+", data)
        for exception_match in exception_matches:
            if IssueKind.UNHANDLED_EXCEPTION not in kinds:
                exception_num = exception_match.removeprefix("Mishandled Exception: ")
                if int(exception_num) > 0:
                    kinds.append(IssueKind.UNHANDLED_EXCEPTION)

        reentrancy_matches = re.findall(r"Reentrancy: [0-9]+", data)
        for reentrancy_match in reentrancy_matches:
            if IssueKind.REENTRANCY not in kinds:
                reentrancy_num = reentrancy_match.removeprefix("Reentrancy: ")
                if int(reentrancy_num) > 0:
                    kinds.append(IssueKind.REENTRANCY)

        selfdestruct_matches = re.findall(r"Suicidal Contract: [0-9]+", data)
        for selfdestruct_match in selfdestruct_matches:
            if IssueKind.UNSAFE_SELFDESTRUCT not in kinds:
                selfdestruct_num = selfdestruct_match.removeprefix(
                    "Suicidal Contract: "
                )
                if int(selfdestruct_num) > 0:
                    kinds.append(IssueKind.UNSAFE_SELFDESTRUCT)

        tx_origin_matches = re.findall(r"Transaction Origin Use: [0-9]+", data)
        for tx_origin_match in tx_origin_matches:
            if IssueKind.TRANSACTION_ORDER_DEPENDENCY not in kinds:
                tx_origin_num = tx_origin_match.removeprefix(
                    "Transaction Origin Use: "
                )
                if int(tx_origin_num) > 0:
                    kinds.append(IssueKind.TRANSACTION_ORDER_DEPENDENCY)

        locking_ether_matches = re.findall(r"Freezing Ether: [0-9]+", data)
        for locking_ether_match in locking_ether_matches:
            if IssueKind.LOCKING_ETHER not in kinds:
                locking_ether_num = locking_ether_match.removeprefix(
                    "Freezing Ether: "
                )
                if int(locking_ether_num) > 0:
                    kinds.append(IssueKind.LOCKING_ETHER)

        require_violation_matches = re.findall(
            r"Requirement Violation: [0-9]+", data
        )
        for require_violation_match in require_violation_matches:
            if IssueKind.REQUIREMENT_VIOLATION not in kinds:
                require_violation_num = require_violation_match.removeprefix(
                    "Requirement Violation: "
                )
                if int(require_violation_num) > 0:
                    kinds.append(IssueKind.REQUIREMENT_VIOLATION)

        checker = Checker("Smartian", "fuzzing")
        issues = []
        location = self.parse_issue_location(log_file)
        for kind in kinds:
            issue = Issue(
                kind,
                "",
                Severity.UNKNOWN,
                Confidence.UNKNOWN,
                location,
                checker,
            )
            issues.append(issue)

        return issues

    def match_location_of_issue_to_annotation(
        self, issue: Issue, annot: BugAnnot
    ):
        """Function to check whether an reported issue is related to a bug
        annotation."""
        return issue.issue_kind == annot.annot_kind

    def parse_instruction_coverage(self, test_output_dir: str):
        """Parse code coverage of Smartian"""
        log_file = os.path.join(test_output_dir, self.log_file)

        lines = None
        try:
            with open(log_file, "r", encoding="utf-8") as file:
                lines = [line.rstrip() for line in file]
        except Exception as err:
            error(f"Failed to parse Smartian log file: {log_file}\n\n{err}")
            return []

        current_time = 0
        contract_coverage = [(0, 0)]
        contract_coverage_list = []

        for line in lines:
            match_str = re.search(r"Covered Instructions: [0-9]+", line)
            time_str = re.search(
                "(\d{2})[/.:](\d{2})[/.:](\d{2})[/.:](\d{2})", line
            )
            if match_str and time_str:
                time = time_str.group()
                seconds = int(time[9:11])
                minutes = int(time[6:8])
                hours = int(time[3:5])
                duration = hours * 3600 + minutes * 60 + seconds

                # Results of new contract
                if duration < current_time:
                    if contract_coverage != []:
                        contract_coverage_list.append(contract_coverage)

                    current_time = duration
                    contract_coverage = [(0,0)]

                # Add a new pair every second
                if duration - current_time >= 1:
                    current_coverage = match_str.group()
                    current_coverage = current_coverage.removeprefix("Covered Instructions: ")
                    contract_coverage.append((duration, int(current_coverage)))
                    current_time = duration

        # Append the last list if it is not empty
        if contract_coverage != []:
            contract_coverage_list.append(contract_coverage)

        prev_contract_time = 0
        prev_contract_instrs = 0
        results = []
        for contract_coverage in contract_coverage_list:
            for (time, instr) in contract_coverage:
                results.append((time + prev_contract_time, instr + prev_contract_instrs))

            prev_contract_time += contract_coverage[-1][0]
            prev_contract_instrs += contract_coverage[-1][1]

        return results
