[info]
id = "smartian"
name = "Smartian"
homepage = "https://github.com/eth-sri/smartian"
category = "Fuzzing"

[command]
path = "..."
default_arguments = ""

[output]
result_file = "smartian_result.json"
log_file = "smartian_log.toml"
