#!/usr/bin/env python3

"""Module handling TOOLNAME."""

# Standard Library
import json
import os

from typing import List, Optional

# Library
from smartbench import log
from smartbench.debug import debug, warning
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.loc import Location


# Tool name
TOOL_NAME = "toolname"


def make_ifl_analysis_command(
    executable_file: str,
    arguments: str,
    test_file: str,
    output_file: str,
    solc_path: str,
):
    """Function to make analysis command for `TOOLNAME`. This function should
    have the same signature with other tools.

    """
    # TODO
    pass


def parse_confidence(confidence: Optional[str]) -> Confidence:
    """Parse confidence level of issue detected by TOOLNAME."""
    # TODO
    pass


def parse_severity(severity: Optional[str]) -> Severity:
    """Parse severity level of issue detected by TOOLNAME."""
    # TODO
    pass


def parse_source_location(log_file, backtrace_elements) -> Location:
    """Parse source location in backtrace elements generated by TOOLNAME."""
    # TODO
    pass


def parse_rule(rule: str) -> Checker:
    """Parser checker of TOOLNAME"""
    # TODO
    pass


def parse_issue_kind(description: str, checker: str) -> IssueKind:
    """Parse issue kind from issue description reported by TOOLNAME"""
    # TODO
    pass


def parse_toolname_json_output(
    output_file: str,
    log_file: str,
) -> List[Issue]:
    """Parse output of TOOLNAME"""
    # TODO
    pass
