[info]
id = "confuzzius"
name = "ConFuzzius"
homepage = "https://github.com/christoftorres/ConFuzzius"
category = "Fuzzing"

[command]
path = "sh smartbench/tools/confuzzius/confuzzius.sh"
default_arguments = ""

[output]
result_file = "confuzzius_result.json"
log_file = "confuzzius_log.toml"
