[info]
id = "confuzzius"
name = "ConFuzzius"
homepage = "https://github.com/christoftorres/ConFuzzius"
category = "Fuzzing"

[command]
path = "python /home/thanhtoantnt/workspace/smartbench-runner/ConFuzzius/fuzzer/main.py"
default_arguments = ""

[output]
result_file = "confuzzius_result.json"
log_file = "confuzzius_log.toml"
