[info]
id = "confuzzius"
name = "ConFuzzius"
homepage = "https://github.com/christoftorres/ConFuzzius"
category = "Fuzzing"

[command]
executable = "bash smartbench/tools/confuzzius/confuzzius.sh"
default_arguments = ""
default_timeout = 60
