#!/usr/bin/env python3

"""Module handling Confuzzius"""

# Standard Library
import json
import os

from typing import List, Optional, Tuple

# Library
from smartbench import bug_annot, log, solc
from smartbench.bug_annot import BugAnnot
from smartbench.debug import debug, warning
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.loc import Location
from smartbench.tools.tool import Tool


class Confuzzius(Tool):
    def __init__(
        self,
        id: str,
        name: str,
        homepage: str,
        category: str,
        path: str,
        default_arguments: str,
        default_timeout: int,
        additional_arguments: Optional[str] = None,
        random_seed: int = 0,
    ):
        Tool.__init__(
            self,
            id,
            name,
            homepage,
            category,
            path,
            default_arguments,
            default_timeout,
            additional_arguments,
            random_seed,
        )

    def make_analysis_command(
        self,
        test_file: str,
        test_output_dir: str,
        timeout=None,
        use_docker=True,
    ) -> Tuple[str, dict]:
        """
        Function to make analysis command for Confuzzius.
        This function should have the same signature with other tools.
        """
        cmd = self.path
        solc_version = solc.detect_required_solc_version(test_file)

        if self.default_arguments:
            cmd = cmd + " " + self.default_arguments
        if self.additional_arguments:
            cmd = cmd + " " + self.additional_arguments

        out_file = self.configure_output_file(test_output_dir)
        timeout = timeout if timeout is not None else self.default_timeout

        # Configure Solc version by environment variable.
        cmd = f"{cmd} -s {test_file} -r {out_file} -t {timeout}"
        env_vars = {"SOLC_VERSION": solc_version}

        return (cmd, env_vars)

    def parse_issue_severity(self, severity: Optional[str]) -> Severity:
        if severity is None:
            return Severity.UNKNOWN

        severity = severity.casefold()

        if severity == "low":
            return Severity.LOW_RISK

        if severity == "medium":
            return Severity.MEDIUM_RISK

        if severity == "high":
            return Severity.HIGH_RISK

        return Severity.UNKNOWN

    def parse_source_location(
        self, log_file: str, line, col
    ) -> Optional[Location]:
        """Parse source location in backtrace elements generated by Confuzzius."""
        file_path = log.get_input_test_file(log_file)
        return Location(file_path, line, col, line, col)

    def parse_issue_kind(self, description: str) -> IssueKind:
        """Parse issue kind from issue description reported by Confuzzius"""
        if "Reentrancy" in description:
            return IssueKind.REENTRANCY

        if "Assertion Failure" in description:
            return IssueKind.ASSERTION_FAILURE

        if "Integer Overflow" in description:
            return IssueKind.INTEGER_BUG

        if "Integer Underflow" in description:
            return IssueKind.INTEGER_BUG

        if "Transaction Order Dependency" in description:
            return IssueKind.TRANSACTION_ORDER_DEPENDENCY

        if "Block Dependency" in description:
            return IssueKind.BLOCK_DEPENDENCY

        if "Leaking Ether" in description:
            return IssueKind.LEAKING_ETHER

        if "Locking Ether" in description:
            return IssueKind.LOCKING_ETHER

        if "Unchecked Return Value" in description:
            return IssueKind.UNHANDLED_EXCEPTION

        if "Unprotected Selfdestruct" in description:
            return IssueKind.UNSAFE_SELFDESTRUCT

        if "Unsafe Delegatecall" in description:
            return IssueKind.UNSAFE_DELEGATECALL

        return IssueKind.UNKNOWN

    def process_analysis_result(
        self,
        test_output_dir: str,
    ) -> List[Issue]:
        """Parse output of Confuzzius"""
        output = None

        output_file = os.path.join(test_output_dir, self.output_file)
        if not os.path.exists(output_file):
            return []

        log_file = os.path.join(test_output_dir, self.log_file)

        debug("Confuzzius parse file: ", output_file)
        with open(output_file, "r", encoding="utf-8") as file:
            try:
                output = json.load(file)
            except ValueError:
                warning("Failed to parse Confuzzius output file:", output_file)
                return []

        if output is None:
            warning("Failed to parse Confuzzius's output file:", output_file)
            return []

        checker = Checker("Confuzzius", "fuzzing")
        try:
            issues = []

            all_results = list(output.values())
            results = all_results[0]
            error_list = results.get("errors")
            errors = list(error_list.values())

            for error_desc in errors:
                error = error_desc[0]
                kind = self.parse_issue_kind(error.get("type"))
                location = self.parse_source_location(
                    log_file, error.get("line"), error.get("column")
                )
                severity = self.parse_issue_severity(error.get("severity"))
                issue = Issue(
                    kind,
                    "",
                    severity,
                    Confidence.UNKNOWN,
                    location,
                    checker,
                )
                issues.append(issue)
            return issues

        except ValueError:
            return []

    def parse_instruction_coverage(self, test_output_dir: str):
        """Parse code coverage of Confuzzius"""
        output_file = os.path.join(test_output_dir, self.output_file)
        output = None

        debug("Confuzzius parse file: ", output_file)
        with open(output_file, "r", encoding="utf-8") as file:
            try:
                output = json.load(file)
            except ValueError:
                warning("Failed to parse Confuzzius output file:", output_file)
                return []

        if output is None:
            warning("Failed to parse Confuzzius's output file:", output_file)
            return []

        try:
            coverages = [(0, 0)]
            current_time = 0

            all_results = list(output.values())
            results = all_results[0]
            generations = results.get("generations")
            # generations = list(generations.values())

            for generation in generations:
                time = float("{:.1f}".format(generation.get("time")))
                coverage = float(
                    "{:.1f}".format(generation.get("code_coverage"))
                )
                if time - current_time >= 1:
                    coverages.append((time, coverage))
                    current_time = time
            return coverages

        except ValueError:
            return []
