#!/usr/bin/env python3

# python3 ~/workspace/ConFuzzius/fuzzer/main.py -s ConFuzzius/examples/TokenSale/contracts/TokenSale.sol --evm byzantium -t 10
"""Module handling Confuzzius"""

# Standard Library
import json
import os

from typing import List, Union

# Library
from smartbench.debug import debug, warning
from smartbench.issue import Checker, Confidence, Issue, IssueKind, Severity
from smartbench.location import Location


# Tool name
TOOL_NAME = "ConFuzzius"


def make_confuzzius_analysis_command(
    executable_file: str,
    arguments: str,
    test_file: str,
    output_file: str,
):
    """
    Function to make analysis command for Confuzzius.
    This function should have the same signature with other tools.
    """
    print("Making confuzzius command")
    command = executable_file

    if arguments:
        command = command + " " + arguments

    command = command + " -s " + test_file + " -r " + output_file + " --evm byzantium" + " -t 20"
    return command


def parse_confidence(confidence: Union[str, None]) -> Confidence:
    """Parse confidence level of issue detected by Confuzzius."""
    if confidence is None:
        return Confidence.UNKNOWN

    confidence = confidence.casefold()

    if confidence == "high":
        return Confidence.HIGH

    if confidence == "low":
        return Confidence.LOW

    if confidence == "medium":
        return Confidence.MEDIUM

    return Confidence.UNKNOWN


def parse_severity(severity: Union[str, None]) -> Severity:
    """Parse severity level of issue detected by Confuzzius."""
    if severity is None:
        return Severity.UNKNOWN

    severity = severity.casefold()

    if severity == "low":
        return Severity.LOW_RISK

    if severity == "medium":
        return Severity.MEDIUM_RISK

    if severity == "high":
        return Severity.HIGH_RISK

    return Severity.UNKNOWN


def parse_source_location(line, col) -> Union[Location, None]:
    """Parse source location in backtrace elements generated by Confuzzius."""

    return Location("", line, col, line, col)


def parse_rule(rule: str) -> Checker:
    """Parser checker of Confuzzius"""
    return Checker("Confuzzius", rule)


def parse_issue_kind(description: str) -> IssueKind:
    """Parse issue kind from issue description reported by Confuzzius"""
    if "Reentrancy" in description:
        return IssueKind.REENTRANCY

    if "Assertion Failure" in description:
        return IssueKind.ASSERTION_FAILURE

    if "Integer Overflow" in description:
        return IssueKind.INTEGER_OVERFLOW

    if "Integer Underflow" in description:
        return IssueKind.INTEGER_UNDERFLOW

    return IssueKind.UNKNOWN


def parse_confuzzius_json_output(
    output_file: str,
) -> List[Issue]:
    """Parse output of Confuzzius"""
    output = None

    debug("Confuzzius parse file: ", output_file)
    with open(output_file, "r", encoding="utf-8") as file:
        try:
            output = json.load(file)
        except ValueError:
            warning("Failed to parse Confuzzius output file:", output_file)
            return []

    if output is None:
        warning("Failed to parse Confuzzius's output file:", output_file)
        return []

    try:
        issues = []

        all_results = list(output.values())
        results = all_results[0]
        error_list = results.get("errors")
        errors = list(error_list.values())

        for error_desc in errors:
            error = error_desc[0]
            checker = parse_rule("fuzzing")
            kind = parse_issue_kind(error.get("type"))
            location = parse_source_location(error.get("line"), error.get("column"))
            severity = parse_severity(error.get("severity"))
            issue = Issue(
                kind,
                "",
                severity,
                Confidence.UNKNOWN,
                location,
                checker,
            )
            issues.append(issue)
        return issues

    except ValueError:
        return []
